'use strict';

const eventsRouter = require('./src/api/generated/events');
module.context.use('/', eventsRouter);

const workflowRouter = require('./src/api/workflow');
const computeNodesRouter = require('./src/api/generated/computeNodes');
const computeNodeStatsRouter = require('./src/api/generated/computeNodeStats');
const filesGeneratedRouter = require('./src/api/generated/files');
const filesRouter = require('./src/api/nodes/files');
const awsSchedulersRouter = require('./src/api/generated/awsSchedulers');
const localSchedulersRouter = require('./src/api/generated/localSchedulers');
const slurmSchedulersRouter = require('./src/api/generated/slurmSchedulers');
const jobDefinitionsRouter = require('./src/api/nodes/jobDefinitions');
const jobProcessStatsRouter = require('./src/api/generated/jobProcessStats');
const resourcesRouter = require('./src/api/generated/resourceRequirements');
const resultsGeneratedRouter = require('./src/api/generated/results');
const resultsRouter = require('./src/api/nodes/results');
const scheduledComputeNodesRouter = require('./src/api/generated/scheduledComputeNodes');
const userDataRouter = require('./src/api/generated/userData');
const workflowConfigRouter = require('./src/api/nodes/workflowConfig');
const workflowStatusRouter = require('./src/api/nodes/workflowStatus');
const edgesRouter = require('./src/api/edges');
const jobsRouter = require('./src/api/nodes/jobs');
const jobsGeneratedRouter = require('./src/api/generated/jobs');
module.context.use('/', workflowRouter);
module.context.use('/', computeNodesRouter);
module.context.use('/', computeNodeStatsRouter);
module.context.use('/', filesGeneratedRouter);
module.context.use('/', filesRouter);
module.context.use('/', awsSchedulersRouter);
module.context.use('/', localSchedulersRouter);
module.context.use('/', slurmSchedulersRouter);
module.context.use('/', jobDefinitionsRouter);
module.context.use('/', jobProcessStatsRouter);
module.context.use('/', resourcesRouter);
module.context.use('/', resultsRouter);
module.context.use('/', resultsGeneratedRouter);
module.context.use('/', scheduledComputeNodesRouter);
module.context.use('/', userDataRouter);
module.context.use('/', workflowConfigRouter);
module.context.use('/', workflowStatusRouter);
module.context.use('/', edgesRouter);
module.context.use('/', jobsRouter);
module.context.use('/', jobsGeneratedRouter);
