'use strict';

const eventsRouter = require('./src/api/generated/events');
module.context.use('/', eventsRouter);

const workflowSpecificationsRouter = require('./src/api/workflowSpecifications');
const workflowsRouter = require('./src/api/workflows');
const computeNodesRouter = require('./src/api/generated/compute_nodes');
const computeNodeStatsRouter = require('./src/api/generated/compute_node_stats');
const filesGeneratedRouter = require('./src/api/generated/files');
const filesRouter = require('./src/api/files');
const awsSchedulersRouter = require('./src/api/generated/aws_schedulers');
const localSchedulersRouter = require('./src/api/generated/local_schedulers');
const slurmSchedulersRouter = require('./src/api/generated/slurm_schedulers');
const jobSpecificationsRouter = require('./src/api/jobSpecifications');
const jobProcessStatsRouter = require('./src/api/generated/job_process_stats');
const resourcesRouter = require('./src/api/generated/resource_requirements');
const resultsGeneratedRouter = require('./src/api/generated/results');
const resultsRouter = require('./src/api/results');
const scheduledComputeNodesRouter = require('./src/api/generated/scheduled_compute_nodes');
const userDataRouter = require('./src/api/generated/user_data');
const workflowConfigRouter = require('./src/api/workflowConfig');
const edgesRouter = require('./src/api/edges');
const jobsRouter = require('./src/api/jobs');
const jobsGeneratedRouter = require('./src/api/generated/jobs');
module.context.use('/', workflowSpecificationsRouter);
module.context.use('/', workflowsRouter);
module.context.use('/', computeNodesRouter);
module.context.use('/', computeNodeStatsRouter);
module.context.use('/', filesGeneratedRouter);
module.context.use('/', filesRouter);
module.context.use('/', awsSchedulersRouter);
module.context.use('/', localSchedulersRouter);
module.context.use('/', slurmSchedulersRouter);
module.context.use('/', jobSpecificationsRouter);
module.context.use('/', jobProcessStatsRouter);
module.context.use('/', resourcesRouter);
module.context.use('/', resultsRouter);
module.context.use('/', resultsGeneratedRouter);
module.context.use('/', scheduledComputeNodesRouter);
module.context.use('/', userDataRouter);
module.context.use('/', workflowConfigRouter);
module.context.use('/', edgesRouter);
module.context.use('/', jobsRouter);
module.context.use('/', jobsGeneratedRouter);
