[tool.bumpversion]
current_version = "0.4.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "torc_package/pyproject.toml"

[[tool.bumpversion.files]]
filename = "db_service/openapi.yaml"

[[tool.bumpversion.files]]
filename = "db_service/src/api/workflows.js"

[[tool.bumpversion.files]]
filename = "db_service/config.json"

[[tool.bumpversion.files]]
filename = "docs/how_tos/getting_started/installation.md"
