repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=50000"]

  - repo: https://github.com/psf/black
    rev: 23.1.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        args: ["-l99"]
        language: python
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # Use the sha / tag you want to point at
    hooks:
      - id: flake8 # works with .flake8 config
        language: python
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--disable=duplicate-code",
          ]
