#!/bin/sh
#
# Pre-commit hook for torc project
# Runs Rust formatting, linting, and markdown formatting
#

set -e

echo '+cargo fmt -- --check'
cargo fmt -- --check

echo '+cargo clippy --all --all-targets --all-features -- -D warnings'
cargo clippy --all --all-targets --all-features -- -D warnings

echo '+dprint check'
dprint check
