# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""jobs_with_edges_model

    JobsWithEdgesModel(;
        jobs=nothing,
    )

    - jobs::Vector{JobWithEdgesModel}
"""
Base.@kwdef mutable struct JobsWithEdgesModel <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobWithEdgesModel} }

    function JobsWithEdgesModel(jobs, )
        OpenAPI.validate_property(JobsWithEdgesModel, Symbol("jobs"), jobs)
        return new(jobs, )
    end
end # type JobsWithEdgesModel

const _property_types_JobsWithEdgesModel = Dict{Symbol,String}(Symbol("jobs")=>"Vector{JobWithEdgesModel}", )
OpenAPI.property_type(::Type{ JobsWithEdgesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobsWithEdgesModel[name]))}

function check_required(o::JobsWithEdgesModel)
    o.jobs === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ JobsWithEdgesModel }, name::Symbol, val)
end
