# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""files_model

    FilesModel(;
        name=nothing,
        path=nothing,
        st_mtime=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String
    - path::String
    - st_mtime::Float64
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct FilesModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    path::Union{Nothing, String} = nothing
    st_mtime::Union{Nothing, Float64} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function FilesModel(name, path, st_mtime, _key, _id, _rev, )
        OpenAPI.validate_property(FilesModel, Symbol("name"), name)
        OpenAPI.validate_property(FilesModel, Symbol("path"), path)
        OpenAPI.validate_property(FilesModel, Symbol("st_mtime"), st_mtime)
        OpenAPI.validate_property(FilesModel, Symbol("_key"), _key)
        OpenAPI.validate_property(FilesModel, Symbol("_id"), _id)
        OpenAPI.validate_property(FilesModel, Symbol("_rev"), _rev)
        return new(name, path, st_mtime, _key, _id, _rev, )
    end
end # type FilesModel

const _property_types_FilesModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("path")=>"String", Symbol("st_mtime")=>"Float64", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ FilesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FilesModel[name]))}

function check_required(o::FilesModel)
    o.path === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ FilesModel }, name::Symbol, val)
end
