# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_resource_requirements_model

    WorkflowResourceRequirementsModel(;
        name=nothing,
        num_cpus=nothing,
        num_gpus=nothing,
        num_nodes=nothing,
        memory="1m",
        runtime="P0DT1M",
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String
    - num_cpus::Int64
    - num_gpus::Int64
    - num_nodes::Int64
    - memory::String
    - runtime::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowResourceRequirementsModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    num_cpus::Union{Nothing, Int64} = nothing
    num_gpus::Union{Nothing, Int64} = nothing
    num_nodes::Union{Nothing, Int64} = nothing
    memory::Union{Nothing, String} = "1m"
    runtime::Union{Nothing, String} = "P0DT1M"
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowResourceRequirementsModel(name, num_cpus, num_gpus, num_nodes, memory, runtime, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("num_cpus"), num_cpus)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("num_gpus"), num_gpus)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("num_nodes"), num_nodes)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("memory"), memory)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("runtime"), runtime)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowResourceRequirementsModel, Symbol("_rev"), _rev)
        return new(name, num_cpus, num_gpus, num_nodes, memory, runtime, _key, _id, _rev, )
    end
end # type WorkflowResourceRequirementsModel

const _property_types_WorkflowResourceRequirementsModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("num_cpus")=>"Int64", Symbol("num_gpus")=>"Int64", Symbol("num_nodes")=>"Int64", Symbol("memory")=>"String", Symbol("runtime")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowResourceRequirementsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowResourceRequirementsModel[name]))}

function check_required(o::WorkflowResourceRequirementsModel)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowResourceRequirementsModel }, name::Symbol, val)
end
