# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""add_jobs_with_edges_response

    AddJobsWithEdgesResponse(;
        items=nothing,
    )

    - items::Vector{JobsModel}
"""
Base.@kwdef mutable struct AddJobsWithEdgesResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobsModel} }

    function AddJobsWithEdgesResponse(items, )
        OpenAPI.validate_property(AddJobsWithEdgesResponse, Symbol("items"), items)
        return new(items, )
    end
end # type AddJobsWithEdgesResponse

const _property_types_AddJobsWithEdgesResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{JobsModel}", )
OpenAPI.property_type(::Type{ AddJobsWithEdgesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AddJobsWithEdgesResponse[name]))}

function check_required(o::AddJobsWithEdgesResponse)
    true
end

function OpenAPI.validate_property(::Type{ AddJobsWithEdgesResponse }, name::Symbol, val)
end
