# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_collection_names_response

    ListCollectionNamesResponse(;
        names=nothing,
    )

    - names::Vector{String}
"""
Base.@kwdef mutable struct ListCollectionNamesResponse <: OpenAPI.APIModel
    names::Union{Nothing, Vector{String}} = nothing

    function ListCollectionNamesResponse(names, )
        OpenAPI.validate_property(ListCollectionNamesResponse, Symbol("names"), names)
        return new(names, )
    end
end # type ListCollectionNamesResponse

const _property_types_ListCollectionNamesResponse = Dict{Symbol,String}(Symbol("names")=>"Vector{String}", )
OpenAPI.property_type(::Type{ ListCollectionNamesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListCollectionNamesResponse[name]))}

function check_required(o::ListCollectionNamesResponse)
    true
end

function OpenAPI.validate_property(::Type{ ListCollectionNamesResponse }, name::Symbol, val)
end
