# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""add_jobs_response

    AddJobsResponse(;
        items=nothing,
    )

    - items::Vector{JobModel}
"""
Base.@kwdef mutable struct AddJobsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobModel} }

    function AddJobsResponse(items, )
        o = new(items, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AddJobsResponse

const _property_types_AddJobsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{JobModel}", )
OpenAPI.property_type(::Type{ AddJobsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AddJobsResponse[name]))}

function OpenAPI.check_required(o::AddJobsResponse)
    true
end

function OpenAPI.validate_properties(o::AddJobsResponse)
    OpenAPI.validate_property(AddJobsResponse, Symbol("items"), o.items)
end

function OpenAPI.validate_property(::Type{ AddJobsResponse }, name::Symbol, val)

end
