# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_required_existing_files_response

    ListRequiredExistingFilesResponse(;
        files=nothing,
    )

    - files::Vector{String}
"""
Base.@kwdef mutable struct ListRequiredExistingFilesResponse <: OpenAPI.APIModel
    files::Union{Nothing, Vector{String}} = nothing

    function ListRequiredExistingFilesResponse(files, )
        OpenAPI.validate_property(ListRequiredExistingFilesResponse, Symbol("files"), files)
        return new(files, )
    end
end # type ListRequiredExistingFilesResponse

const _property_types_ListRequiredExistingFilesResponse = Dict{Symbol,String}(Symbol("files")=>"Vector{String}", )
OpenAPI.property_type(::Type{ ListRequiredExistingFilesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListRequiredExistingFilesResponse[name]))}

function check_required(o::ListRequiredExistingFilesResponse)
    true
end

function OpenAPI.validate_property(::Type{ ListRequiredExistingFilesResponse }, name::Symbol, val)
end
