# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""post_workflows_key_prepare_jobs_for_scheduling_response

    PostWorkflowsKeyPrepareJobsForSchedulingResponse(;
        schedulers=nothing,
    )

    - schedulers::Vector{String}
"""
Base.@kwdef mutable struct PostWorkflowsKeyPrepareJobsForSchedulingResponse <: OpenAPI.APIModel
    schedulers::Union{Nothing, Vector{String}} = nothing

    function PostWorkflowsKeyPrepareJobsForSchedulingResponse(schedulers, )
        OpenAPI.validate_property(PostWorkflowsKeyPrepareJobsForSchedulingResponse, Symbol("schedulers"), schedulers)
        return new(schedulers, )
    end
end # type PostWorkflowsKeyPrepareJobsForSchedulingResponse

const _property_types_PostWorkflowsKeyPrepareJobsForSchedulingResponse = Dict{Symbol,String}(Symbol("schedulers")=>"Vector{String}", )
OpenAPI.property_type(::Type{ PostWorkflowsKeyPrepareJobsForSchedulingResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PostWorkflowsKeyPrepareJobsForSchedulingResponse[name]))}

function check_required(o::PostWorkflowsKeyPrepareJobsForSchedulingResponse)
    true
end

function OpenAPI.validate_property(::Type{ PostWorkflowsKeyPrepareJobsForSchedulingResponse }, name::Symbol, val)
end
