# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_model

    WorkflowModel(;
        name=nothing,
        user=nothing,
        description=nothing,
        timestamp=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String : Name of the workflow
    - user::String : User that created the workflow
    - description::String : Description of the workflow
    - timestamp::String : Timestamp of workflow creation
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    user::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    timestamp::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowModel(name, user, description, timestamp, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowModel, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowModel, Symbol("user"), user)
        OpenAPI.validate_property(WorkflowModel, Symbol("description"), description)
        OpenAPI.validate_property(WorkflowModel, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(WorkflowModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowModel, Symbol("_rev"), _rev)
        return new(name, user, description, timestamp, _key, _id, _rev, )
    end
end # type WorkflowModel

const _property_types_WorkflowModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("user")=>"String", Symbol("description")=>"String", Symbol("timestamp")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowModel[name]))}

function check_required(o::WorkflowModel)
    o.user === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowModel }, name::Symbol, val)
end
