# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""compute_node_stats_model

    ComputeNodeStatsModel(;
        hostname=nothing,
        stats=nothing,
        timestamp=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - hostname::String
    - stats::Vector{ComputeNodeStats}
    - timestamp::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct ComputeNodeStatsModel <: OpenAPI.APIModel
    hostname::Union{Nothing, String} = nothing
    stats::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ComputeNodeStats} }
    timestamp::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function ComputeNodeStatsModel(hostname, stats, timestamp, _key, _id, _rev, )
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("hostname"), hostname)
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("stats"), stats)
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("_key"), _key)
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("_id"), _id)
        OpenAPI.validate_property(ComputeNodeStatsModel, Symbol("_rev"), _rev)
        return new(hostname, stats, timestamp, _key, _id, _rev, )
    end
end # type ComputeNodeStatsModel

const _property_types_ComputeNodeStatsModel = Dict{Symbol,String}(Symbol("hostname")=>"String", Symbol("stats")=>"Vector{ComputeNodeStats}", Symbol("timestamp")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ ComputeNodeStatsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ComputeNodeStatsModel[name]))}

function check_required(o::ComputeNodeStatsModel)
    o.hostname === nothing && (return false)
    o.timestamp === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ComputeNodeStatsModel }, name::Symbol, val)
end
