# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_scheduled_compute_nodes_model

    WorkflowScheduledComputeNodesModel(;
        scheduler_id=nothing,
        scheduler_config_id=nothing,
        status=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - scheduler_id::String
    - scheduler_config_id::String
    - status::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowScheduledComputeNodesModel <: OpenAPI.APIModel
    scheduler_id::Union{Nothing, String} = nothing
    scheduler_config_id::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowScheduledComputeNodesModel(scheduler_id, scheduler_config_id, status, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("scheduler_id"), scheduler_id)
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("scheduler_config_id"), scheduler_config_id)
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("status"), status)
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowScheduledComputeNodesModel, Symbol("_rev"), _rev)
        return new(scheduler_id, scheduler_config_id, status, _key, _id, _rev, )
    end
end # type WorkflowScheduledComputeNodesModel

const _property_types_WorkflowScheduledComputeNodesModel = Dict{Symbol,String}(Symbol("scheduler_id")=>"String", Symbol("scheduler_config_id")=>"String", Symbol("status")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowScheduledComputeNodesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowScheduledComputeNodesModel[name]))}

function check_required(o::WorkflowScheduledComputeNodesModel)
    o.scheduler_config_id === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowScheduledComputeNodesModel }, name::Symbol, val)
end
