# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""user_data_model

    UserDataModel(;
        is_ephemeral=false,
        name=nothing,
        data=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - is_ephemeral::Bool : The data will only exist for the duration of one run. Torc will clear it before starting new runs.
    - name::String : Name of the data object
    - data::Any : User-defined data
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct UserDataModel <: OpenAPI.APIModel
    is_ephemeral::Union{Nothing, Bool} = false
    name::Union{Nothing, String} = nothing
    data::Union{Nothing, Any} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function UserDataModel(is_ephemeral, name, data, _key, _id, _rev, )
        OpenAPI.validate_property(UserDataModel, Symbol("is_ephemeral"), is_ephemeral)
        OpenAPI.validate_property(UserDataModel, Symbol("name"), name)
        OpenAPI.validate_property(UserDataModel, Symbol("data"), data)
        OpenAPI.validate_property(UserDataModel, Symbol("_key"), _key)
        OpenAPI.validate_property(UserDataModel, Symbol("_id"), _id)
        OpenAPI.validate_property(UserDataModel, Symbol("_rev"), _rev)
        return new(is_ephemeral, name, data, _key, _id, _rev, )
    end
end # type UserDataModel

const _property_types_UserDataModel = Dict{Symbol,String}(Symbol("is_ephemeral")=>"Bool", Symbol("name")=>"String", Symbol("data")=>"Any", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ UserDataModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserDataModel[name]))}

function check_required(o::UserDataModel)
    true
end

function OpenAPI.validate_property(::Type{ UserDataModel }, name::Symbol, val)
end
