# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""prepare_jobs_for_scheduling_response

    PrepareJobsForSchedulingResponse(;
        schedulers=nothing,
    )

    - schedulers::Vector{String}
"""
Base.@kwdef mutable struct PrepareJobsForSchedulingResponse <: OpenAPI.APIModel
    schedulers::Union{Nothing, Vector{String}} = nothing

    function PrepareJobsForSchedulingResponse(schedulers, )
        OpenAPI.validate_property(PrepareJobsForSchedulingResponse, Symbol("schedulers"), schedulers)
        return new(schedulers, )
    end
end # type PrepareJobsForSchedulingResponse

const _property_types_PrepareJobsForSchedulingResponse = Dict{Symbol,String}(Symbol("schedulers")=>"Vector{String}", )
OpenAPI.property_type(::Type{ PrepareJobsForSchedulingResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PrepareJobsForSchedulingResponse[name]))}

function check_required(o::PrepareJobsForSchedulingResponse)
    true
end

function OpenAPI.validate_property(::Type{ PrepareJobsForSchedulingResponse }, name::Symbol, val)
end
