# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""job_with_edges_model

    JobWithEdgesModel(;
        job=nothing,
        resource_requirements=nothing,
        scheduler=nothing,
        input_files=nothing,
        output_files=nothing,
        input_user_data=nothing,
        output_user_data=nothing,
        blocked_by=nothing,
    )

    - job::WorkflowJobsModel
    - resource_requirements::String
    - scheduler::String
    - input_files::Vector{String}
    - output_files::Vector{String}
    - input_user_data::Vector{String}
    - output_user_data::Vector{String}
    - blocked_by::Vector{String}
"""
Base.@kwdef mutable struct JobWithEdgesModel <: OpenAPI.APIModel
    job = nothing # spec type: Union{ Nothing, WorkflowJobsModel }
    resource_requirements::Union{Nothing, String} = nothing
    scheduler::Union{Nothing, String} = nothing
    input_files::Union{Nothing, Vector{String}} = nothing
    output_files::Union{Nothing, Vector{String}} = nothing
    input_user_data::Union{Nothing, Vector{String}} = nothing
    output_user_data::Union{Nothing, Vector{String}} = nothing
    blocked_by::Union{Nothing, Vector{String}} = nothing

    function JobWithEdgesModel(job, resource_requirements, scheduler, input_files, output_files, input_user_data, output_user_data, blocked_by, )
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("job"), job)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("resource_requirements"), resource_requirements)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("scheduler"), scheduler)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("input_files"), input_files)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("output_files"), output_files)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("input_user_data"), input_user_data)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("output_user_data"), output_user_data)
        OpenAPI.validate_property(JobWithEdgesModel, Symbol("blocked_by"), blocked_by)
        return new(job, resource_requirements, scheduler, input_files, output_files, input_user_data, output_user_data, blocked_by, )
    end
end # type JobWithEdgesModel

const _property_types_JobWithEdgesModel = Dict{Symbol,String}(Symbol("job")=>"WorkflowJobsModel", Symbol("resource_requirements")=>"String", Symbol("scheduler")=>"String", Symbol("input_files")=>"Vector{String}", Symbol("output_files")=>"Vector{String}", Symbol("input_user_data")=>"Vector{String}", Symbol("output_user_data")=>"Vector{String}", Symbol("blocked_by")=>"Vector{String}", )
OpenAPI.property_type(::Type{ JobWithEdgesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobWithEdgesModel[name]))}

function check_required(o::JobWithEdgesModel)
    o.job === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ JobWithEdgesModel }, name::Symbol, val)
end
