# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_results_model

    WorkflowResultsModel(;
        job_key=nothing,
        run_id=nothing,
        return_code=nothing,
        exec_time_minutes=nothing,
        completion_time=nothing,
        status=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - job_key::String
    - run_id::Int64
    - return_code::Int64
    - exec_time_minutes::Float64
    - completion_time::String
    - status::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowResultsModel <: OpenAPI.APIModel
    job_key::Union{Nothing, String} = nothing
    run_id::Union{Nothing, Int64} = nothing
    return_code::Union{Nothing, Int64} = nothing
    exec_time_minutes::Union{Nothing, Float64} = nothing
    completion_time::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowResultsModel(job_key, run_id, return_code, exec_time_minutes, completion_time, status, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("job_key"), job_key)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("run_id"), run_id)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("return_code"), return_code)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("exec_time_minutes"), exec_time_minutes)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("completion_time"), completion_time)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("status"), status)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowResultsModel, Symbol("_rev"), _rev)
        return new(job_key, run_id, return_code, exec_time_minutes, completion_time, status, _key, _id, _rev, )
    end
end # type WorkflowResultsModel

const _property_types_WorkflowResultsModel = Dict{Symbol,String}(Symbol("job_key")=>"String", Symbol("run_id")=>"Int64", Symbol("return_code")=>"Int64", Symbol("exec_time_minutes")=>"Float64", Symbol("completion_time")=>"String", Symbol("status")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowResultsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowResultsModel[name]))}

function check_required(o::WorkflowResultsModel)
    o.job_key === nothing && (return false)
    o.run_id === nothing && (return false)
    o.return_code === nothing && (return false)
    o.exec_time_minutes === nothing && (return false)
    o.completion_time === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowResultsModel }, name::Symbol, val)
end
