# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""post_workflows_key_process_changed_job_inputs_response

    PostWorkflowsKeyProcessChangedJobInputsResponse(;
        reinitialized_jobs=nothing,
    )

    - reinitialized_jobs::Vector{String}
"""
Base.@kwdef mutable struct PostWorkflowsKeyProcessChangedJobInputsResponse <: OpenAPI.APIModel
    reinitialized_jobs::Union{Nothing, Vector{String}} = nothing

    function PostWorkflowsKeyProcessChangedJobInputsResponse(reinitialized_jobs, )
        OpenAPI.validate_property(PostWorkflowsKeyProcessChangedJobInputsResponse, Symbol("reinitialized_jobs"), reinitialized_jobs)
        return new(reinitialized_jobs, )
    end
end # type PostWorkflowsKeyProcessChangedJobInputsResponse

const _property_types_PostWorkflowsKeyProcessChangedJobInputsResponse = Dict{Symbol,String}(Symbol("reinitialized_jobs")=>"Vector{String}", )
OpenAPI.property_type(::Type{ PostWorkflowsKeyProcessChangedJobInputsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PostWorkflowsKeyProcessChangedJobInputsResponse[name]))}

function check_required(o::PostWorkflowsKeyProcessChangedJobInputsResponse)
    true
end

function OpenAPI.validate_property(::Type{ PostWorkflowsKeyProcessChangedJobInputsResponse }, name::Symbol, val)
end
