# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""local_schedulers_model

    LocalSchedulersModel(;
        name="default",
        memory=nothing,
        num_cpus=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String
    - memory::String
    - num_cpus::Int64
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct LocalSchedulersModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = "default"
    memory::Union{Nothing, String} = nothing
    num_cpus::Union{Nothing, Int64} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function LocalSchedulersModel(name, memory, num_cpus, _key, _id, _rev, )
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("name"), name)
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("memory"), memory)
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("num_cpus"), num_cpus)
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("_key"), _key)
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("_id"), _id)
        OpenAPI.validate_property(LocalSchedulersModel, Symbol("_rev"), _rev)
        return new(name, memory, num_cpus, _key, _id, _rev, )
    end
end # type LocalSchedulersModel

const _property_types_LocalSchedulersModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("memory")=>"String", Symbol("num_cpus")=>"Int64", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ LocalSchedulersModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LocalSchedulersModel[name]))}

function check_required(o::LocalSchedulersModel)
    true
end

function OpenAPI.validate_property(::Type{ LocalSchedulersModel }, name::Symbol, val)
end
