# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_files_produced_by_job

    ListFilesProducedByJob(;
        items=nothing,
        skip=nothing,
        max_limit=nothing,
        count=nothing,
        total_count=nothing,
        has_more=nothing,
    )

    - items::Vector{FileModel}
    - skip::Int64
    - max_limit::Int64
    - count::Int64
    - total_count::Int64
    - has_more::Bool
"""
Base.@kwdef mutable struct ListFilesProducedByJob <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FileModel} }
    skip::Union{Nothing, Int64} = nothing
    max_limit::Union{Nothing, Int64} = nothing
    count::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function ListFilesProducedByJob(items, skip, max_limit, count, total_count, has_more, )
        o = new(items, skip, max_limit, count, total_count, has_more, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListFilesProducedByJob

const _property_types_ListFilesProducedByJob = Dict{Symbol,String}(Symbol("items")=>"Vector{FileModel}", Symbol("skip")=>"Int64", Symbol("max_limit")=>"Int64", Symbol("count")=>"Int64", Symbol("total_count")=>"Int64", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ ListFilesProducedByJob }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListFilesProducedByJob[name]))}

function OpenAPI.check_required(o::ListFilesProducedByJob)
    o.skip === nothing && (return false)
    o.max_limit === nothing && (return false)
    o.count === nothing && (return false)
    o.total_count === nothing && (return false)
    o.has_more === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ListFilesProducedByJob)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("items"), o.items)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("skip"), o.skip)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("max_limit"), o.max_limit)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("count"), o.count)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("total_count"), o.total_count)
    OpenAPI.validate_property(ListFilesProducedByJob, Symbol("has_more"), o.has_more)
end

function OpenAPI.validate_property(::Type{ ListFilesProducedByJob }, name::Symbol, val)






end
