# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_aws_schedulers_model

    WorkflowAwsSchedulersModel(;
        name=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowAwsSchedulersModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowAwsSchedulersModel(name, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowAwsSchedulersModel, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowAwsSchedulersModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowAwsSchedulersModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowAwsSchedulersModel, Symbol("_rev"), _rev)
        return new(name, _key, _id, _rev, )
    end
end # type WorkflowAwsSchedulersModel

const _property_types_WorkflowAwsSchedulersModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowAwsSchedulersModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowAwsSchedulersModel[name]))}

function check_required(o::WorkflowAwsSchedulersModel)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowAwsSchedulersModel }, name::Symbol, val)
end
