# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflows_model

    WorkflowsModel(;
        name=nothing,
        user=nothing,
        description=nothing,
        timestamp=nothing,
        _key=nothing,
        _id=nothing,
        _rev=nothing,
    )

    - name::String
    - user::String
    - description::String
    - timestamp::String
    - _key::String
    - _id::String
    - _rev::String
"""
Base.@kwdef mutable struct WorkflowsModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    user::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    timestamp::Union{Nothing, String} = nothing
    _key::Union{Nothing, String} = nothing
    _id::Union{Nothing, String} = nothing
    _rev::Union{Nothing, String} = nothing

    function WorkflowsModel(name, user, description, timestamp, _key, _id, _rev, )
        OpenAPI.validate_property(WorkflowsModel, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowsModel, Symbol("user"), user)
        OpenAPI.validate_property(WorkflowsModel, Symbol("description"), description)
        OpenAPI.validate_property(WorkflowsModel, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(WorkflowsModel, Symbol("_key"), _key)
        OpenAPI.validate_property(WorkflowsModel, Symbol("_id"), _id)
        OpenAPI.validate_property(WorkflowsModel, Symbol("_rev"), _rev)
        return new(name, user, description, timestamp, _key, _id, _rev, )
    end
end # type WorkflowsModel

const _property_types_WorkflowsModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("user")=>"String", Symbol("description")=>"String", Symbol("timestamp")=>"String", Symbol("_key")=>"String", Symbol("_id")=>"String", Symbol("_rev")=>"String", )
OpenAPI.property_type(::Type{ WorkflowsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowsModel[name]))}

function check_required(o::WorkflowsModel)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowsModel }, name::Symbol, val)
end
