# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""bulk_jobs_with_edges_model

    BulkJobsWithEdgesModel(;
        jobs=nothing,
    )

    - jobs::Vector{JobWithEdgesModel}
"""
Base.@kwdef mutable struct BulkJobsWithEdgesModel <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobWithEdgesModel} }

    function BulkJobsWithEdgesModel(jobs, )
        OpenAPI.validate_property(BulkJobsWithEdgesModel, Symbol("jobs"), jobs)
        return new(jobs, )
    end
end # type BulkJobsWithEdgesModel

const _property_types_BulkJobsWithEdgesModel = Dict{Symbol,String}(Symbol("jobs")=>"Vector{JobWithEdgesModel}", )
OpenAPI.property_type(::Type{ BulkJobsWithEdgesModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BulkJobsWithEdgesModel[name]))}

function check_required(o::BulkJobsWithEdgesModel)
    o.jobs === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ BulkJobsWithEdgesModel }, name::Symbol, val)
end
