# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""workflow_specification_model

    WorkflowSpecificationModel(;
        name=nothing,
        key=nothing,
        user=nothing,
        description=nothing,
        jobs=nothing,
        files=nothing,
        user_data=nothing,
        resource_requirements=nothing,
        schedulers=nothing,
        config=nothing,
    )

    - name::String : Name of the workflow
    - key::String : Optional key to use as the database identifier. If set, it must be unique in the database. It is recommended to let the database create the identifier.
    - user::String : User that created the workflow
    - description::String : Timestamp of workflow creation
    - jobs::Vector{JobSpecificationModel} : Jobs in the workflow. Each job name must be unique.
    - files::Vector{FileModel} : Files in the workflow. Each file name must be unique.
    - user_data::Vector{UserDataModel} : User data in the workflow. Each name must be unique.
    - resource_requirements::Vector{ResourceRequirementsModel} : Resource requirements in the workflow. Each name must be unique.
    - schedulers::WorkflowSpecificationsSchedulers
    - config::WorkflowConfigModel
"""
Base.@kwdef mutable struct WorkflowSpecificationModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    key::Union{Nothing, String} = nothing
    user::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobSpecificationModel} }
    files::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FileModel} }
    user_data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{UserDataModel} }
    resource_requirements::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ResourceRequirementsModel} }
    schedulers = nothing # spec type: Union{ Nothing, WorkflowSpecificationsSchedulers }
    config = nothing # spec type: Union{ Nothing, WorkflowConfigModel }

    function WorkflowSpecificationModel(name, key, user, description, jobs, files, user_data, resource_requirements, schedulers, config, )
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("key"), key)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("user"), user)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("description"), description)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("jobs"), jobs)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("files"), files)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("user_data"), user_data)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("resource_requirements"), resource_requirements)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("schedulers"), schedulers)
        OpenAPI.validate_property(WorkflowSpecificationModel, Symbol("config"), config)
        return new(name, key, user, description, jobs, files, user_data, resource_requirements, schedulers, config, )
    end
end # type WorkflowSpecificationModel

const _property_types_WorkflowSpecificationModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("key")=>"String", Symbol("user")=>"String", Symbol("description")=>"String", Symbol("jobs")=>"Vector{JobSpecificationModel}", Symbol("files")=>"Vector{FileModel}", Symbol("user_data")=>"Vector{UserDataModel}", Symbol("resource_requirements")=>"Vector{ResourceRequirementsModel}", Symbol("schedulers")=>"WorkflowSpecificationsSchedulers", Symbol("config")=>"WorkflowConfigModel", )
OpenAPI.property_type(::Type{ WorkflowSpecificationModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowSpecificationModel[name]))}

function check_required(o::WorkflowSpecificationModel)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowSpecificationModel }, name::Symbol, val)
end
