# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""job_specifications_model

    JobSpecificationsModel(;
        name=nothing,
        key=nothing,
        command=nothing,
        invocation_script=nothing,
        cancel_on_blocking_job_failure=true,
        supports_termination=false,
        scheduler=nothing,
        needs_compute_node_schedule=false,
        input_user_data=nothing,
        output_user_data=nothing,
        resource_requirements=nothing,
        input_files=nothing,
        output_files=nothing,
        blocked_by=nothing,
    )

    - name::String
    - key::String
    - command::String
    - invocation_script::String
    - cancel_on_blocking_job_failure::Bool
    - supports_termination::Bool
    - scheduler::String
    - needs_compute_node_schedule::Bool
    - input_user_data::Vector{String}
    - output_user_data::Vector{String}
    - resource_requirements::String
    - input_files::Vector{String}
    - output_files::Vector{String}
    - blocked_by::Vector{String}
"""
Base.@kwdef mutable struct JobSpecificationsModel <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    key::Union{Nothing, String} = nothing
    command::Union{Nothing, String} = nothing
    invocation_script::Union{Nothing, String} = nothing
    cancel_on_blocking_job_failure::Union{Nothing, Bool} = true
    supports_termination::Union{Nothing, Bool} = false
    scheduler::Union{Nothing, String} = nothing
    needs_compute_node_schedule::Union{Nothing, Bool} = false
    input_user_data::Union{Nothing, Vector{String}} = nothing
    output_user_data::Union{Nothing, Vector{String}} = nothing
    resource_requirements::Union{Nothing, String} = nothing
    input_files::Union{Nothing, Vector{String}} = nothing
    output_files::Union{Nothing, Vector{String}} = nothing
    blocked_by::Union{Nothing, Vector{String}} = nothing

    function JobSpecificationsModel(name, key, command, invocation_script, cancel_on_blocking_job_failure, supports_termination, scheduler, needs_compute_node_schedule, input_user_data, output_user_data, resource_requirements, input_files, output_files, blocked_by, )
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("name"), name)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("key"), key)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("command"), command)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("invocation_script"), invocation_script)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("cancel_on_blocking_job_failure"), cancel_on_blocking_job_failure)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("supports_termination"), supports_termination)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("scheduler"), scheduler)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("needs_compute_node_schedule"), needs_compute_node_schedule)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("input_user_data"), input_user_data)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("output_user_data"), output_user_data)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("resource_requirements"), resource_requirements)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("input_files"), input_files)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("output_files"), output_files)
        OpenAPI.validate_property(JobSpecificationsModel, Symbol("blocked_by"), blocked_by)
        return new(name, key, command, invocation_script, cancel_on_blocking_job_failure, supports_termination, scheduler, needs_compute_node_schedule, input_user_data, output_user_data, resource_requirements, input_files, output_files, blocked_by, )
    end
end # type JobSpecificationsModel

const _property_types_JobSpecificationsModel = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("key")=>"String", Symbol("command")=>"String", Symbol("invocation_script")=>"String", Symbol("cancel_on_blocking_job_failure")=>"Bool", Symbol("supports_termination")=>"Bool", Symbol("scheduler")=>"String", Symbol("needs_compute_node_schedule")=>"Bool", Symbol("input_user_data")=>"Vector{String}", Symbol("output_user_data")=>"Vector{String}", Symbol("resource_requirements")=>"String", Symbol("input_files")=>"Vector{String}", Symbol("output_files")=>"Vector{String}", Symbol("blocked_by")=>"Vector{String}", )
OpenAPI.property_type(::Type{ JobSpecificationsModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobSpecificationsModel[name]))}

function check_required(o::JobSpecificationsModel)
    o.command === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ JobSpecificationsModel }, name::Symbol, val)
end
