# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""get_workflows_workflow_events_response

    GetWorkflowsWorkflowEventsResponse(;
        items=nothing,
        skip=nothing,
        max_limit=nothing,
        count=nothing,
        total_count=nothing,
        has_more=nothing,
    )

    - items::Vector{Any}
    - skip::Int64
    - max_limit::Int64
    - count::Int64
    - total_count::Int64
    - has_more::Bool
"""
Base.@kwdef mutable struct GetWorkflowsWorkflowEventsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector{Any}} = nothing
    skip::Union{Nothing, Int64} = nothing
    max_limit::Union{Nothing, Int64} = nothing
    count::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function GetWorkflowsWorkflowEventsResponse(items, skip, max_limit, count, total_count, has_more, )
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("items"), items)
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("skip"), skip)
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("max_limit"), max_limit)
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("count"), count)
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("total_count"), total_count)
        OpenAPI.validate_property(GetWorkflowsWorkflowEventsResponse, Symbol("has_more"), has_more)
        return new(items, skip, max_limit, count, total_count, has_more, )
    end
end # type GetWorkflowsWorkflowEventsResponse

const _property_types_GetWorkflowsWorkflowEventsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{Any}", Symbol("skip")=>"Int64", Symbol("max_limit")=>"Int64", Symbol("count")=>"Int64", Symbol("total_count")=>"Int64", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ GetWorkflowsWorkflowEventsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetWorkflowsWorkflowEventsResponse[name]))}

function check_required(o::GetWorkflowsWorkflowEventsResponse)
    o.skip === nothing && (return false)
    o.max_limit === nothing && (return false)
    o.count === nothing && (return false)
    o.total_count === nothing && (return false)
    o.has_more === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetWorkflowsWorkflowEventsResponse }, name::Symbol, val)
end
