# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scheduled_by_edge_model import (
    ScheduledByEdgeModel,
)  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduledByEdgeModel(unittest.TestCase):
    """ScheduledByEdgeModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledByEdgeModel(self):
        """Test ScheduledByEdgeModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scheduled_by_edge_model.ScheduledByEdgeModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
