# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20030(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_canceled': 'bool',
        'run_id': 'int',
        'auto_tune_status': 'WorkflowskeystatusAutoTuneStatus',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'is_canceled': 'is_canceled',
        'run_id': 'run_id',
        'auto_tune_status': 'auto_tune_status',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, is_canceled=None, run_id=None, auto_tune_status=None, key=None, id=None, rev=None):  # noqa: E501
        """InlineResponse20030 - a model defined in Swagger"""  # noqa: E501
        self._is_canceled = None
        self._run_id = None
        self._auto_tune_status = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        self.is_canceled = is_canceled
        self.run_id = run_id
        self.auto_tune_status = auto_tune_status
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def is_canceled(self):
        """Gets the is_canceled of this InlineResponse20030.  # noqa: E501


        :return: The is_canceled of this InlineResponse20030.  # noqa: E501
        :rtype: bool
        """
        return self._is_canceled

    @is_canceled.setter
    def is_canceled(self, is_canceled):
        """Sets the is_canceled of this InlineResponse20030.


        :param is_canceled: The is_canceled of this InlineResponse20030.  # noqa: E501
        :type: bool
        """
        if is_canceled is None:
            raise ValueError("Invalid value for `is_canceled`, must not be `None`")  # noqa: E501

        self._is_canceled = is_canceled

    @property
    def run_id(self):
        """Gets the run_id of this InlineResponse20030.  # noqa: E501


        :return: The run_id of this InlineResponse20030.  # noqa: E501
        :rtype: int
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this InlineResponse20030.


        :param run_id: The run_id of this InlineResponse20030.  # noqa: E501
        :type: int
        """
        if run_id is None:
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501

        self._run_id = run_id

    @property
    def auto_tune_status(self):
        """Gets the auto_tune_status of this InlineResponse20030.  # noqa: E501


        :return: The auto_tune_status of this InlineResponse20030.  # noqa: E501
        :rtype: WorkflowskeystatusAutoTuneStatus
        """
        return self._auto_tune_status

    @auto_tune_status.setter
    def auto_tune_status(self, auto_tune_status):
        """Sets the auto_tune_status of this InlineResponse20030.


        :param auto_tune_status: The auto_tune_status of this InlineResponse20030.  # noqa: E501
        :type: WorkflowskeystatusAutoTuneStatus
        """
        if auto_tune_status is None:
            raise ValueError("Invalid value for `auto_tune_status`, must not be `None`")  # noqa: E501

        self._auto_tune_status = auto_tune_status

    @property
    def key(self):
        """Gets the key of this InlineResponse20030.  # noqa: E501


        :return: The key of this InlineResponse20030.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this InlineResponse20030.


        :param key: The key of this InlineResponse20030.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this InlineResponse20030.  # noqa: E501


        :return: The id of this InlineResponse20030.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20030.


        :param id: The id of this InlineResponse20030.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this InlineResponse20030.  # noqa: E501


        :return: The rev of this InlineResponse20030.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this InlineResponse20030.


        :param rev: The rev of this InlineResponse20030.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20030, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20030):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
