# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20020(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'key': 'str',
        'user': 'object',
        'description': 'object',
        'jobs': 'list[WorkflowJobSpecificationsModel]',
        'files': 'list[FilesKeyModel]',
        'user_data': 'list[KeyUserDataModel]',
        'resource_requirements': 'list[ResourceRequirementsKeyModel]',
        'schedulers': 'WorkflowSpecificationsSchedulers',
        'config': 'KeyConfigModel'
    }

    attribute_map = {
        'name': 'name',
        'key': 'key',
        'user': 'user',
        'description': 'description',
        'jobs': 'jobs',
        'files': 'files',
        'user_data': 'user_data',
        'resource_requirements': 'resource_requirements',
        'schedulers': 'schedulers',
        'config': 'config'
    }

    def __init__(self, name=None, key=None, user=None, description=None, jobs=None, files=None, user_data=None, resource_requirements=None, schedulers=None, config=None):  # noqa: E501
        """InlineResponse20020 - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._key = None
        self._user = None
        self._description = None
        self._jobs = None
        self._files = None
        self._user_data = None
        self._resource_requirements = None
        self._schedulers = None
        self._config = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if key is not None:
            self.key = key
        if user is not None:
            self.user = user
        if description is not None:
            self.description = description
        if jobs is not None:
            self.jobs = jobs
        if files is not None:
            self.files = files
        if user_data is not None:
            self.user_data = user_data
        if resource_requirements is not None:
            self.resource_requirements = resource_requirements
        if schedulers is not None:
            self.schedulers = schedulers
        if config is not None:
            self.config = config

    @property
    def name(self):
        """Gets the name of this InlineResponse20020.  # noqa: E501


        :return: The name of this InlineResponse20020.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20020.


        :param name: The name of this InlineResponse20020.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def key(self):
        """Gets the key of this InlineResponse20020.  # noqa: E501


        :return: The key of this InlineResponse20020.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this InlineResponse20020.


        :param key: The key of this InlineResponse20020.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def user(self):
        """Gets the user of this InlineResponse20020.  # noqa: E501


        :return: The user of this InlineResponse20020.  # noqa: E501
        :rtype: object
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this InlineResponse20020.


        :param user: The user of this InlineResponse20020.  # noqa: E501
        :type: object
        """

        self._user = user

    @property
    def description(self):
        """Gets the description of this InlineResponse20020.  # noqa: E501


        :return: The description of this InlineResponse20020.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse20020.


        :param description: The description of this InlineResponse20020.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def jobs(self):
        """Gets the jobs of this InlineResponse20020.  # noqa: E501


        :return: The jobs of this InlineResponse20020.  # noqa: E501
        :rtype: list[WorkflowJobSpecificationsModel]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs):
        """Sets the jobs of this InlineResponse20020.


        :param jobs: The jobs of this InlineResponse20020.  # noqa: E501
        :type: list[WorkflowJobSpecificationsModel]
        """

        self._jobs = jobs

    @property
    def files(self):
        """Gets the files of this InlineResponse20020.  # noqa: E501


        :return: The files of this InlineResponse20020.  # noqa: E501
        :rtype: list[FilesKeyModel]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this InlineResponse20020.


        :param files: The files of this InlineResponse20020.  # noqa: E501
        :type: list[FilesKeyModel]
        """

        self._files = files

    @property
    def user_data(self):
        """Gets the user_data of this InlineResponse20020.  # noqa: E501


        :return: The user_data of this InlineResponse20020.  # noqa: E501
        :rtype: list[KeyUserDataModel]
        """
        return self._user_data

    @user_data.setter
    def user_data(self, user_data):
        """Sets the user_data of this InlineResponse20020.


        :param user_data: The user_data of this InlineResponse20020.  # noqa: E501
        :type: list[KeyUserDataModel]
        """

        self._user_data = user_data

    @property
    def resource_requirements(self):
        """Gets the resource_requirements of this InlineResponse20020.  # noqa: E501


        :return: The resource_requirements of this InlineResponse20020.  # noqa: E501
        :rtype: list[ResourceRequirementsKeyModel]
        """
        return self._resource_requirements

    @resource_requirements.setter
    def resource_requirements(self, resource_requirements):
        """Sets the resource_requirements of this InlineResponse20020.


        :param resource_requirements: The resource_requirements of this InlineResponse20020.  # noqa: E501
        :type: list[ResourceRequirementsKeyModel]
        """

        self._resource_requirements = resource_requirements

    @property
    def schedulers(self):
        """Gets the schedulers of this InlineResponse20020.  # noqa: E501


        :return: The schedulers of this InlineResponse20020.  # noqa: E501
        :rtype: WorkflowSpecificationsSchedulers
        """
        return self._schedulers

    @schedulers.setter
    def schedulers(self, schedulers):
        """Sets the schedulers of this InlineResponse20020.


        :param schedulers: The schedulers of this InlineResponse20020.  # noqa: E501
        :type: WorkflowSpecificationsSchedulers
        """

        self._schedulers = schedulers

    @property
    def config(self):
        """Gets the config of this InlineResponse20020.  # noqa: E501


        :return: The config of this InlineResponse20020.  # noqa: E501
        :rtype: KeyConfigModel
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this InlineResponse20020.


        :param config: The config of this InlineResponse20020.  # noqa: E501
        :type: KeyConfigModel
        """

        self._config = config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20020, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20020):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
