# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeyPrepareJobsForSubmissionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'num_cpus': 'int',
        'memory_gb': 'float',
        'num_gpus': 'int',
        'num_nodes': 'int',
        'time_limit': 'object',
        'scheduler_config_id': 'str'
    }

    attribute_map = {
        'num_cpus': 'num_cpus',
        'memory_gb': 'memory_gb',
        'num_gpus': 'num_gpus',
        'num_nodes': 'num_nodes',
        'time_limit': 'time_limit',
        'scheduler_config_id': 'scheduler_config_id'
    }

    def __init__(self, num_cpus=None, memory_gb=None, num_gpus=None, num_nodes=None, time_limit=None, scheduler_config_id=None):  # noqa: E501
        """KeyPrepareJobsForSubmissionModel - a model defined in Swagger"""  # noqa: E501
        self._num_cpus = None
        self._memory_gb = None
        self._num_gpus = None
        self._num_nodes = None
        self._time_limit = None
        self._scheduler_config_id = None
        self.discriminator = None
        self.num_cpus = num_cpus
        self.memory_gb = memory_gb
        if num_gpus is not None:
            self.num_gpus = num_gpus
        if num_nodes is not None:
            self.num_nodes = num_nodes
        if time_limit is not None:
            self.time_limit = time_limit
        if scheduler_config_id is not None:
            self.scheduler_config_id = scheduler_config_id

    @property
    def num_cpus(self):
        """Gets the num_cpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The num_cpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: int
        """
        return self._num_cpus

    @num_cpus.setter
    def num_cpus(self, num_cpus):
        """Sets the num_cpus of this KeyPrepareJobsForSubmissionModel.


        :param num_cpus: The num_cpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: int
        """
        if num_cpus is None:
            raise ValueError("Invalid value for `num_cpus`, must not be `None`")  # noqa: E501

        self._num_cpus = num_cpus

    @property
    def memory_gb(self):
        """Gets the memory_gb of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The memory_gb of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: float
        """
        return self._memory_gb

    @memory_gb.setter
    def memory_gb(self, memory_gb):
        """Sets the memory_gb of this KeyPrepareJobsForSubmissionModel.


        :param memory_gb: The memory_gb of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: float
        """
        if memory_gb is None:
            raise ValueError("Invalid value for `memory_gb`, must not be `None`")  # noqa: E501

        self._memory_gb = memory_gb

    @property
    def num_gpus(self):
        """Gets the num_gpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The num_gpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: int
        """
        return self._num_gpus

    @num_gpus.setter
    def num_gpus(self, num_gpus):
        """Sets the num_gpus of this KeyPrepareJobsForSubmissionModel.


        :param num_gpus: The num_gpus of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: int
        """

        self._num_gpus = num_gpus

    @property
    def num_nodes(self):
        """Gets the num_nodes of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The num_nodes of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: int
        """
        return self._num_nodes

    @num_nodes.setter
    def num_nodes(self, num_nodes):
        """Sets the num_nodes of this KeyPrepareJobsForSubmissionModel.


        :param num_nodes: The num_nodes of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: int
        """

        self._num_nodes = num_nodes

    @property
    def time_limit(self):
        """Gets the time_limit of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The time_limit of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: object
        """
        return self._time_limit

    @time_limit.setter
    def time_limit(self, time_limit):
        """Sets the time_limit of this KeyPrepareJobsForSubmissionModel.


        :param time_limit: The time_limit of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: object
        """

        self._time_limit = time_limit

    @property
    def scheduler_config_id(self):
        """Gets the scheduler_config_id of this KeyPrepareJobsForSubmissionModel.  # noqa: E501


        :return: The scheduler_config_id of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :rtype: str
        """
        return self._scheduler_config_id

    @scheduler_config_id.setter
    def scheduler_config_id(self, scheduler_config_id):
        """Sets the scheduler_config_id of this KeyPrepareJobsForSubmissionModel.


        :param scheduler_config_id: The scheduler_config_id of this KeyPrepareJobsForSubmissionModel.  # noqa: E501
        :type: str
        """

        self._scheduler_config_id = scheduler_config_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeyPrepareJobsForSubmissionModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeyPrepareJobsForSubmissionModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
