# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowLocalSchedulersModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'memory': 'str',
        'num_cpus': 'int',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'name': 'name',
        'memory': 'memory',
        'num_cpus': 'num_cpus',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, name='default', memory=None, num_cpus=None, key=None, id=None, rev=None):  # noqa: E501
        """WorkflowLocalSchedulersModel - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._memory = None
        self._num_cpus = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if memory is not None:
            self.memory = memory
        if num_cpus is not None:
            self.num_cpus = num_cpus
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The name of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowLocalSchedulersModel.


        :param name: The name of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def memory(self):
        """Gets the memory of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The memory of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: str
        """
        return self._memory

    @memory.setter
    def memory(self, memory):
        """Sets the memory of this WorkflowLocalSchedulersModel.


        :param memory: The memory of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: str
        """

        self._memory = memory

    @property
    def num_cpus(self):
        """Gets the num_cpus of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The num_cpus of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: int
        """
        return self._num_cpus

    @num_cpus.setter
    def num_cpus(self, num_cpus):
        """Sets the num_cpus of this WorkflowLocalSchedulersModel.


        :param num_cpus: The num_cpus of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: int
        """

        self._num_cpus = num_cpus

    @property
    def key(self):
        """Gets the key of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The key of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this WorkflowLocalSchedulersModel.


        :param key: The key of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The id of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowLocalSchedulersModel.


        :param id: The id of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this WorkflowLocalSchedulersModel.  # noqa: E501


        :return: The rev of this WorkflowLocalSchedulersModel.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this WorkflowLocalSchedulersModel.


        :param rev: The rev of this WorkflowLocalSchedulersModel.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowLocalSchedulersModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowLocalSchedulersModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
