# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowScheduledComputeNodesModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scheduler_id': 'str',
        'scheduler_config_id': 'str',
        'status': 'str',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'scheduler_id': 'scheduler_id',
        'scheduler_config_id': 'scheduler_config_id',
        'status': 'status',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, scheduler_id=None, scheduler_config_id=None, status=None, key=None, id=None, rev=None):  # noqa: E501
        """WorkflowScheduledComputeNodesModel - a model defined in Swagger"""  # noqa: E501
        self._scheduler_id = None
        self._scheduler_config_id = None
        self._status = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        if scheduler_id is not None:
            self.scheduler_id = scheduler_id
        self.scheduler_config_id = scheduler_config_id
        self.status = status
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def scheduler_id(self):
        """Gets the scheduler_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The scheduler_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._scheduler_id

    @scheduler_id.setter
    def scheduler_id(self, scheduler_id):
        """Sets the scheduler_id of this WorkflowScheduledComputeNodesModel.


        :param scheduler_id: The scheduler_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """

        self._scheduler_id = scheduler_id

    @property
    def scheduler_config_id(self):
        """Gets the scheduler_config_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The scheduler_config_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._scheduler_config_id

    @scheduler_config_id.setter
    def scheduler_config_id(self, scheduler_config_id):
        """Sets the scheduler_config_id of this WorkflowScheduledComputeNodesModel.


        :param scheduler_config_id: The scheduler_config_id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """
        if scheduler_config_id is None:
            raise ValueError("Invalid value for `scheduler_config_id`, must not be `None`")  # noqa: E501

        self._scheduler_config_id = scheduler_config_id

    @property
    def status(self):
        """Gets the status of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The status of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WorkflowScheduledComputeNodesModel.


        :param status: The status of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def key(self):
        """Gets the key of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The key of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this WorkflowScheduledComputeNodesModel.


        :param key: The key of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowScheduledComputeNodesModel.


        :param id: The id of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this WorkflowScheduledComputeNodesModel.  # noqa: E501


        :return: The rev of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this WorkflowScheduledComputeNodesModel.


        :param rev: The rev of this WorkflowScheduledComputeNodesModel.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowScheduledComputeNodesModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowScheduledComputeNodesModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
