# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowskeystatusAutoTuneStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'job_keys': 'list[str]'
    }

    attribute_map = {
        'enabled': 'enabled',
        'job_keys': 'job_keys'
    }

    def __init__(self, enabled=False, job_keys=None):  # noqa: E501
        """WorkflowskeystatusAutoTuneStatus - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._job_keys = None
        self.discriminator = None
        if enabled is not None:
            self.enabled = enabled
        if job_keys is not None:
            self.job_keys = job_keys

    @property
    def enabled(self):
        """Gets the enabled of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501


        :return: The enabled of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this WorkflowskeystatusAutoTuneStatus.


        :param enabled: The enabled of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def job_keys(self):
        """Gets the job_keys of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501


        :return: The job_keys of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501
        :rtype: list[str]
        """
        return self._job_keys

    @job_keys.setter
    def job_keys(self, job_keys):
        """Sets the job_keys of this WorkflowskeystatusAutoTuneStatus.


        :param job_keys: The job_keys of this WorkflowskeystatusAutoTuneStatus.  # noqa: E501
        :type: list[str]
        """

        self._job_keys = job_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowskeystatusAutoTuneStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowskeystatusAutoTuneStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
