# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'user': 'str',
        'description': 'str',
        'timestamp': 'str',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'name': 'name',
        'user': 'user',
        'description': 'description',
        'timestamp': 'timestamp',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, name=None, user=None, description=None, timestamp=None, key=None, id=None, rev=None):  # noqa: E501
        """WorkflowsModel - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._user = None
        self._description = None
        self._timestamp = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if user is not None:
            self.user = user
        if description is not None:
            self.description = description
        if timestamp is not None:
            self.timestamp = timestamp
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this WorkflowsModel.  # noqa: E501


        :return: The name of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowsModel.


        :param name: The name of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def user(self):
        """Gets the user of this WorkflowsModel.  # noqa: E501


        :return: The user of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this WorkflowsModel.


        :param user: The user of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def description(self):
        """Gets the description of this WorkflowsModel.  # noqa: E501


        :return: The description of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WorkflowsModel.


        :param description: The description of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def timestamp(self):
        """Gets the timestamp of this WorkflowsModel.  # noqa: E501


        :return: The timestamp of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this WorkflowsModel.


        :param timestamp: The timestamp of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def key(self):
        """Gets the key of this WorkflowsModel.  # noqa: E501


        :return: The key of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this WorkflowsModel.


        :param key: The key of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this WorkflowsModel.  # noqa: E501


        :return: The id of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowsModel.


        :param id: The id of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this WorkflowsModel.  # noqa: E501


        :return: The rev of this WorkflowsModel.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this WorkflowsModel.


        :param rev: The rev of this WorkflowsModel.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowsModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
