# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FileModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'path': 'str',
        'file_hash': 'str',
        'st_mtime': 'str',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'name': 'name',
        'path': 'path',
        'file_hash': 'file_hash',
        'st_mtime': 'st_mtime',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, name=None, path=None, file_hash=None, st_mtime=None, key=None, id=None, rev=None):  # noqa: E501
        """FileModel - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._path = None
        self._file_hash = None
        self._st_mtime = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        self.name = name
        self.path = path
        if file_hash is not None:
            self.file_hash = file_hash
        if st_mtime is not None:
            self.st_mtime = st_mtime
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this FileModel.  # noqa: E501


        :return: The name of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FileModel.


        :param name: The name of this FileModel.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def path(self):
        """Gets the path of this FileModel.  # noqa: E501


        :return: The path of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this FileModel.


        :param path: The path of this FileModel.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def file_hash(self):
        """Gets the file_hash of this FileModel.  # noqa: E501


        :return: The file_hash of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._file_hash

    @file_hash.setter
    def file_hash(self, file_hash):
        """Sets the file_hash of this FileModel.


        :param file_hash: The file_hash of this FileModel.  # noqa: E501
        :type: str
        """

        self._file_hash = file_hash

    @property
    def st_mtime(self):
        """Gets the st_mtime of this FileModel.  # noqa: E501


        :return: The st_mtime of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._st_mtime

    @st_mtime.setter
    def st_mtime(self, st_mtime):
        """Sets the st_mtime of this FileModel.


        :param st_mtime: The st_mtime of this FileModel.  # noqa: E501
        :type: str
        """

        self._st_mtime = st_mtime

    @property
    def key(self):
        """Gets the key of this FileModel.  # noqa: E501


        :return: The key of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this FileModel.


        :param key: The key of this FileModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this FileModel.  # noqa: E501


        :return: The id of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FileModel.


        :param id: The id of this FileModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this FileModel.  # noqa: E501


        :return: The rev of this FileModel.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this FileModel.


        :param rev: The rev of this FileModel.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
