# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse500(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'object',
        'error_num': 'int',
        'error_message': 'str',
        'code': 'int'
    }

    attribute_map = {
        'error': 'error',
        'error_num': 'errorNum',
        'error_message': 'errorMessage',
        'code': 'code'
    }

    def __init__(self, error=None, error_num=None, error_message=None, code=None):  # noqa: E501
        """InlineResponse500 - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._error_num = None
        self._error_message = None
        self._code = None
        self.discriminator = None
        self.error = error
        if error_num is not None:
            self.error_num = error_num
        if error_message is not None:
            self.error_message = error_message
        if code is not None:
            self.code = code

    @property
    def error(self):
        """Gets the error of this InlineResponse500.  # noqa: E501


        :return: The error of this InlineResponse500.  # noqa: E501
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse500.


        :param error: The error of this InlineResponse500.  # noqa: E501
        :type: object
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def error_num(self):
        """Gets the error_num of this InlineResponse500.  # noqa: E501


        :return: The error_num of this InlineResponse500.  # noqa: E501
        :rtype: int
        """
        return self._error_num

    @error_num.setter
    def error_num(self, error_num):
        """Sets the error_num of this InlineResponse500.


        :param error_num: The error_num of this InlineResponse500.  # noqa: E501
        :type: int
        """

        self._error_num = error_num

    @property
    def error_message(self):
        """Gets the error_message of this InlineResponse500.  # noqa: E501


        :return: The error_message of this InlineResponse500.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this InlineResponse500.


        :param error_message: The error_message of this InlineResponse500.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def code(self):
        """Gets the code of this InlineResponse500.  # noqa: E501


        :return: The code of this InlineResponse500.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse500.


        :param code: The code of this InlineResponse500.  # noqa: E501
        :type: int
        """

        self._code = code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse500, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse500):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
