# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'command': 'str',
        'cancel_on_blocking_job_failure': 'bool',
        'scheduler': 'str',
        'resource_requirements': 'str',
        'input_files': 'list[str]',
        'output_files': 'list[str]',
        'blocked_by': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'command': 'command',
        'cancel_on_blocking_job_failure': 'cancel_on_blocking_job_failure',
        'scheduler': 'scheduler',
        'resource_requirements': 'resource_requirements',
        'input_files': 'input_files',
        'output_files': 'output_files',
        'blocked_by': 'blocked_by'
    }

    def __init__(self, name=None, command=None, cancel_on_blocking_job_failure=True, scheduler=None, resource_requirements=None, input_files=None, output_files=None, blocked_by=None):  # noqa: E501
        """JobDefinition - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._command = None
        self._cancel_on_blocking_job_failure = None
        self._scheduler = None
        self._resource_requirements = None
        self._input_files = None
        self._output_files = None
        self._blocked_by = None
        self.discriminator = None
        self.name = name
        self.command = command
        if cancel_on_blocking_job_failure is not None:
            self.cancel_on_blocking_job_failure = cancel_on_blocking_job_failure
        if scheduler is not None:
            self.scheduler = scheduler
        if resource_requirements is not None:
            self.resource_requirements = resource_requirements
        if input_files is not None:
            self.input_files = input_files
        if output_files is not None:
            self.output_files = output_files
        if blocked_by is not None:
            self.blocked_by = blocked_by

    @property
    def name(self):
        """Gets the name of this JobDefinition.  # noqa: E501


        :return: The name of this JobDefinition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JobDefinition.


        :param name: The name of this JobDefinition.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def command(self):
        """Gets the command of this JobDefinition.  # noqa: E501


        :return: The command of this JobDefinition.  # noqa: E501
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this JobDefinition.


        :param command: The command of this JobDefinition.  # noqa: E501
        :type: str
        """
        if command is None:
            raise ValueError("Invalid value for `command`, must not be `None`")  # noqa: E501

        self._command = command

    @property
    def cancel_on_blocking_job_failure(self):
        """Gets the cancel_on_blocking_job_failure of this JobDefinition.  # noqa: E501


        :return: The cancel_on_blocking_job_failure of this JobDefinition.  # noqa: E501
        :rtype: bool
        """
        return self._cancel_on_blocking_job_failure

    @cancel_on_blocking_job_failure.setter
    def cancel_on_blocking_job_failure(self, cancel_on_blocking_job_failure):
        """Sets the cancel_on_blocking_job_failure of this JobDefinition.


        :param cancel_on_blocking_job_failure: The cancel_on_blocking_job_failure of this JobDefinition.  # noqa: E501
        :type: bool
        """

        self._cancel_on_blocking_job_failure = cancel_on_blocking_job_failure

    @property
    def scheduler(self):
        """Gets the scheduler of this JobDefinition.  # noqa: E501


        :return: The scheduler of this JobDefinition.  # noqa: E501
        :rtype: str
        """
        return self._scheduler

    @scheduler.setter
    def scheduler(self, scheduler):
        """Sets the scheduler of this JobDefinition.


        :param scheduler: The scheduler of this JobDefinition.  # noqa: E501
        :type: str
        """

        self._scheduler = scheduler

    @property
    def resource_requirements(self):
        """Gets the resource_requirements of this JobDefinition.  # noqa: E501


        :return: The resource_requirements of this JobDefinition.  # noqa: E501
        :rtype: str
        """
        return self._resource_requirements

    @resource_requirements.setter
    def resource_requirements(self, resource_requirements):
        """Sets the resource_requirements of this JobDefinition.


        :param resource_requirements: The resource_requirements of this JobDefinition.  # noqa: E501
        :type: str
        """

        self._resource_requirements = resource_requirements

    @property
    def input_files(self):
        """Gets the input_files of this JobDefinition.  # noqa: E501


        :return: The input_files of this JobDefinition.  # noqa: E501
        :rtype: list[str]
        """
        return self._input_files

    @input_files.setter
    def input_files(self, input_files):
        """Sets the input_files of this JobDefinition.


        :param input_files: The input_files of this JobDefinition.  # noqa: E501
        :type: list[str]
        """

        self._input_files = input_files

    @property
    def output_files(self):
        """Gets the output_files of this JobDefinition.  # noqa: E501


        :return: The output_files of this JobDefinition.  # noqa: E501
        :rtype: list[str]
        """
        return self._output_files

    @output_files.setter
    def output_files(self, output_files):
        """Sets the output_files of this JobDefinition.


        :param output_files: The output_files of this JobDefinition.  # noqa: E501
        :type: list[str]
        """

        self._output_files = output_files

    @property
    def blocked_by(self):
        """Gets the blocked_by of this JobDefinition.  # noqa: E501


        :return: The blocked_by of this JobDefinition.  # noqa: E501
        :rtype: list[str]
        """
        return self._blocked_by

    @blocked_by.setter
    def blocked_by(self, blocked_by):
        """Sets the blocked_by of this JobDefinition.


        :param blocked_by: The blocked_by of this JobDefinition.  # noqa: E501
        :type: list[str]
        """

        self._blocked_by = blocked_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
