# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ResourceRequirementsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "name": "str",
        "num_cpus": "float",
        "num_gpus": "float",
        "memory": "str",
        "runtime": "str",
        "key": "str",
        "id": "str",
        "rev": "str",
    }

    attribute_map = {
        "name": "name",
        "num_cpus": "num_cpus",
        "num_gpus": "num_gpus",
        "memory": "memory",
        "runtime": "runtime",
        "key": "_key",
        "id": "_id",
        "rev": "_rev",
    }

    def __init__(
        self,
        name=None,
        num_cpus=None,
        num_gpus=None,
        memory="1m",
        runtime="P0DT1H",
        key=None,
        id=None,
        rev=None,
    ):  # noqa: E501
        """ResourceRequirementsModel - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._num_cpus = None
        self._num_gpus = None
        self._memory = None
        self._runtime = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        self.name = name
        if num_cpus is not None:
            self.num_cpus = num_cpus
        if num_gpus is not None:
            self.num_gpus = num_gpus
        if memory is not None:
            self.memory = memory
        if runtime is not None:
            self.runtime = runtime
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this ResourceRequirementsModel.  # noqa: E501


        :return: The name of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResourceRequirementsModel.


        :param name: The name of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def num_cpus(self):
        """Gets the num_cpus of this ResourceRequirementsModel.  # noqa: E501


        :return: The num_cpus of this ResourceRequirementsModel.  # noqa: E501
        :rtype: float
        """
        return self._num_cpus

    @num_cpus.setter
    def num_cpus(self, num_cpus):
        """Sets the num_cpus of this ResourceRequirementsModel.


        :param num_cpus: The num_cpus of this ResourceRequirementsModel.  # noqa: E501
        :type: float
        """

        self._num_cpus = num_cpus

    @property
    def num_gpus(self):
        """Gets the num_gpus of this ResourceRequirementsModel.  # noqa: E501


        :return: The num_gpus of this ResourceRequirementsModel.  # noqa: E501
        :rtype: float
        """
        return self._num_gpus

    @num_gpus.setter
    def num_gpus(self, num_gpus):
        """Sets the num_gpus of this ResourceRequirementsModel.


        :param num_gpus: The num_gpus of this ResourceRequirementsModel.  # noqa: E501
        :type: float
        """

        self._num_gpus = num_gpus

    @property
    def memory(self):
        """Gets the memory of this ResourceRequirementsModel.  # noqa: E501


        :return: The memory of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._memory

    @memory.setter
    def memory(self, memory):
        """Sets the memory of this ResourceRequirementsModel.


        :param memory: The memory of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """

        self._memory = memory

    @property
    def runtime(self):
        """Gets the runtime of this ResourceRequirementsModel.  # noqa: E501


        :return: The runtime of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this ResourceRequirementsModel.


        :param runtime: The runtime of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """

        self._runtime = runtime

    @property
    def key(self):
        """Gets the key of this ResourceRequirementsModel.  # noqa: E501


        :return: The key of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ResourceRequirementsModel.


        :param key: The key of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this ResourceRequirementsModel.  # noqa: E501


        :return: The id of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ResourceRequirementsModel.


        :param id: The id of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this ResourceRequirementsModel.  # noqa: E501


        :return: The rev of this ResourceRequirementsModel.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this ResourceRequirementsModel.


        :param rev: The rev of this ResourceRequirementsModel.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ResourceRequirementsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceRequirementsModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
