# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StoreUserDataNameBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'return_code': 'float',
        'exec_time_minutes': 'float',
        'completion_time': 'str',
        'status': 'str',
        'key': 'str',
        'id': 'str',
        'rev': 'str'
    }

    attribute_map = {
        'name': 'name',
        'return_code': 'return_code',
        'exec_time_minutes': 'exec_time_minutes',
        'completion_time': 'completion_time',
        'status': 'status',
        'key': '_key',
        'id': '_id',
        'rev': '_rev'
    }

    def __init__(self, name=None, return_code=None, exec_time_minutes=None, completion_time=None, status=None, key=None, id=None, rev=None):  # noqa: E501
        """StoreUserDataNameBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._return_code = None
        self._exec_time_minutes = None
        self._completion_time = None
        self._status = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        self.name = name
        self.return_code = return_code
        self.exec_time_minutes = exec_time_minutes
        self.completion_time = completion_time
        self.status = status
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this StoreUserDataNameBody.  # noqa: E501


        :return: The name of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StoreUserDataNameBody.


        :param name: The name of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def return_code(self):
        """Gets the return_code of this StoreUserDataNameBody.  # noqa: E501


        :return: The return_code of this StoreUserDataNameBody.  # noqa: E501
        :rtype: float
        """
        return self._return_code

    @return_code.setter
    def return_code(self, return_code):
        """Sets the return_code of this StoreUserDataNameBody.


        :param return_code: The return_code of this StoreUserDataNameBody.  # noqa: E501
        :type: float
        """
        if return_code is None:
            raise ValueError("Invalid value for `return_code`, must not be `None`")  # noqa: E501

        self._return_code = return_code

    @property
    def exec_time_minutes(self):
        """Gets the exec_time_minutes of this StoreUserDataNameBody.  # noqa: E501


        :return: The exec_time_minutes of this StoreUserDataNameBody.  # noqa: E501
        :rtype: float
        """
        return self._exec_time_minutes

    @exec_time_minutes.setter
    def exec_time_minutes(self, exec_time_minutes):
        """Sets the exec_time_minutes of this StoreUserDataNameBody.


        :param exec_time_minutes: The exec_time_minutes of this StoreUserDataNameBody.  # noqa: E501
        :type: float
        """
        if exec_time_minutes is None:
            raise ValueError("Invalid value for `exec_time_minutes`, must not be `None`")  # noqa: E501

        self._exec_time_minutes = exec_time_minutes

    @property
    def completion_time(self):
        """Gets the completion_time of this StoreUserDataNameBody.  # noqa: E501


        :return: The completion_time of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._completion_time

    @completion_time.setter
    def completion_time(self, completion_time):
        """Sets the completion_time of this StoreUserDataNameBody.


        :param completion_time: The completion_time of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """
        if completion_time is None:
            raise ValueError("Invalid value for `completion_time`, must not be `None`")  # noqa: E501

        self._completion_time = completion_time

    @property
    def status(self):
        """Gets the status of this StoreUserDataNameBody.  # noqa: E501


        :return: The status of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StoreUserDataNameBody.


        :param status: The status of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def key(self):
        """Gets the key of this StoreUserDataNameBody.  # noqa: E501


        :return: The key of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this StoreUserDataNameBody.


        :param key: The key of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this StoreUserDataNameBody.  # noqa: E501


        :return: The id of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StoreUserDataNameBody.


        :param id: The id of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this StoreUserDataNameBody.  # noqa: E501


        :return: The rev of this StoreUserDataNameBody.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this StoreUserDataNameBody.


        :param rev: The rev of this StoreUserDataNameBody.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoreUserDataNameBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoreUserDataNameBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
