# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class WorkflowSchedulers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "name": "str",
        "hpc_type": "str",
        "account": "str",
        "partition": "str",
        "qos": "str",
        "walltime": "str",
        "key": "str",
        "id": "str",
        "rev": "str",
    }

    attribute_map = {
        "name": "name",
        "hpc_type": "hpc_type",
        "account": "account",
        "partition": "partition",
        "qos": "qos",
        "walltime": "walltime",
        "key": "_key",
        "id": "_id",
        "rev": "_rev",
    }

    def __init__(
        self,
        name=None,
        hpc_type=None,
        account=None,
        partition=None,
        qos="normal",
        walltime=None,
        key=None,
        id=None,
        rev=None,
    ):  # noqa: E501
        """WorkflowSchedulers - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._hpc_type = None
        self._account = None
        self._partition = None
        self._qos = None
        self._walltime = None
        self._key = None
        self._id = None
        self._rev = None
        self.discriminator = None
        self.name = name
        self.hpc_type = hpc_type
        self.account = account
        if partition is not None:
            self.partition = partition
        if qos is not None:
            self.qos = qos
        if walltime is not None:
            self.walltime = walltime
        if key is not None:
            self.key = key
        if id is not None:
            self.id = id
        if rev is not None:
            self.rev = rev

    @property
    def name(self):
        """Gets the name of this WorkflowSchedulers.  # noqa: E501


        :return: The name of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowSchedulers.


        :param name: The name of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def hpc_type(self):
        """Gets the hpc_type of this WorkflowSchedulers.  # noqa: E501


        :return: The hpc_type of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._hpc_type

    @hpc_type.setter
    def hpc_type(self, hpc_type):
        """Sets the hpc_type of this WorkflowSchedulers.


        :param hpc_type: The hpc_type of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """
        if hpc_type is None:
            raise ValueError(
                "Invalid value for `hpc_type`, must not be `None`"
            )  # noqa: E501

        self._hpc_type = hpc_type

    @property
    def account(self):
        """Gets the account of this WorkflowSchedulers.  # noqa: E501


        :return: The account of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this WorkflowSchedulers.


        :param account: The account of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """
        if account is None:
            raise ValueError(
                "Invalid value for `account`, must not be `None`"
            )  # noqa: E501

        self._account = account

    @property
    def partition(self):
        """Gets the partition of this WorkflowSchedulers.  # noqa: E501


        :return: The partition of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._partition

    @partition.setter
    def partition(self, partition):
        """Sets the partition of this WorkflowSchedulers.


        :param partition: The partition of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._partition = partition

    @property
    def qos(self):
        """Gets the qos of this WorkflowSchedulers.  # noqa: E501


        :return: The qos of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._qos

    @qos.setter
    def qos(self, qos):
        """Sets the qos of this WorkflowSchedulers.


        :param qos: The qos of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._qos = qos

    @property
    def walltime(self):
        """Gets the walltime of this WorkflowSchedulers.  # noqa: E501


        :return: The walltime of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._walltime

    @walltime.setter
    def walltime(self, walltime):
        """Sets the walltime of this WorkflowSchedulers.


        :param walltime: The walltime of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._walltime = walltime

    @property
    def key(self):
        """Gets the key of this WorkflowSchedulers.  # noqa: E501


        :return: The key of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this WorkflowSchedulers.


        :param key: The key of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def id(self):
        """Gets the id of this WorkflowSchedulers.  # noqa: E501


        :return: The id of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowSchedulers.


        :param id: The id of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rev(self):
        """Gets the rev of this WorkflowSchedulers.  # noqa: E501


        :return: The rev of this WorkflowSchedulers.  # noqa: E501
        :rtype: str
        """
        return self._rev

    @rev.setter
    def rev(self, rev):
        """Sets the rev of this WorkflowSchedulers.


        :param rev: The rev of this WorkflowSchedulers.  # noqa: E501
        :type: str
        """

        self._rev = rev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(WorkflowSchedulers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowSchedulers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
