# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""access_group_model
Access group for team-based access control

    AccessGroupModel(;
        id=nothing,
        name=nothing,
        description=nothing,
        created_at=nothing,
    )

    - id::Int64
    - name::String
    - description::String
    - created_at::String
"""
Base.@kwdef mutable struct AccessGroupModel <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    created_at::Union{Nothing, String} = nothing

    function AccessGroupModel(id, name, description, created_at, )
        o = new(id, name, description, created_at, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AccessGroupModel

const _property_types_AccessGroupModel = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("created_at")=>"String", )
OpenAPI.property_type(::Type{ AccessGroupModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccessGroupModel[name]))}

function OpenAPI.check_required(o::AccessGroupModel)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AccessGroupModel)
    OpenAPI.validate_property(AccessGroupModel, Symbol("id"), o.id)
    OpenAPI.validate_property(AccessGroupModel, Symbol("name"), o.name)
    OpenAPI.validate_property(AccessGroupModel, Symbol("description"), o.description)
    OpenAPI.validate_property(AccessGroupModel, Symbol("created_at"), o.created_at)
end

function OpenAPI.validate_property(::Type{ AccessGroupModel }, name::Symbol, val)




end
