# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""prepare_jobs_for_submission_response

    PrepareJobsForSubmissionResponse(;
        jobs=nothing,
        reason=nothing,
    )

    - jobs::Vector{JobModel}
    - reason::String
"""
Base.@kwdef mutable struct PrepareJobsForSubmissionResponse <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobModel} }
    reason::Union{Nothing, String} = nothing

    function PrepareJobsForSubmissionResponse(jobs, reason, )
        o = new(jobs, reason, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PrepareJobsForSubmissionResponse

const _property_types_PrepareJobsForSubmissionResponse = Dict{Symbol,String}(Symbol("jobs")=>"Vector{JobModel}", Symbol("reason")=>"String", )
OpenAPI.property_type(::Type{ PrepareJobsForSubmissionResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PrepareJobsForSubmissionResponse[name]))}

function OpenAPI.check_required(o::PrepareJobsForSubmissionResponse)
    true
end

function OpenAPI.validate_properties(o::PrepareJobsForSubmissionResponse)
    OpenAPI.validate_property(PrepareJobsForSubmissionResponse, Symbol("jobs"), o.jobs)
    OpenAPI.validate_property(PrepareJobsForSubmissionResponse, Symbol("reason"), o.reason)
end

function OpenAPI.validate_property(::Type{ PrepareJobsForSubmissionResponse }, name::Symbol, val)


end
