# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_access_groups_response
Response for listing access groups

    ListAccessGroupsResponse(;
        items=nothing,
        offset=nothing,
        limit=nothing,
        total_count=nothing,
        has_more=nothing,
    )

    - items::Vector{AccessGroupModel}
    - offset::Int64
    - limit::Int64
    - total_count::Int64
    - has_more::Bool
"""
Base.@kwdef mutable struct ListAccessGroupsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{AccessGroupModel} }
    offset::Union{Nothing, Int64} = nothing
    limit::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function ListAccessGroupsResponse(items, offset, limit, total_count, has_more, )
        o = new(items, offset, limit, total_count, has_more, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListAccessGroupsResponse

const _property_types_ListAccessGroupsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{AccessGroupModel}", Symbol("offset")=>"Int64", Symbol("limit")=>"Int64", Symbol("total_count")=>"Int64", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ ListAccessGroupsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListAccessGroupsResponse[name]))}

function OpenAPI.check_required(o::ListAccessGroupsResponse)
    true
end

function OpenAPI.validate_properties(o::ListAccessGroupsResponse)
    OpenAPI.validate_property(ListAccessGroupsResponse, Symbol("items"), o.items)
    OpenAPI.validate_property(ListAccessGroupsResponse, Symbol("offset"), o.offset)
    OpenAPI.validate_property(ListAccessGroupsResponse, Symbol("limit"), o.limit)
    OpenAPI.validate_property(ListAccessGroupsResponse, Symbol("total_count"), o.total_count)
    OpenAPI.validate_property(ListAccessGroupsResponse, Symbol("has_more"), o.has_more)
end

function OpenAPI.validate_property(::Type{ ListAccessGroupsResponse }, name::Symbol, val)





end
