# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""not_found_error_response

    NotFoundErrorResponse(;
        error=nothing,
        errorNum=nothing,
        errorMessage=nothing,
        code=nothing,
    )

    - error::Any
    - errorNum::Int64
    - errorMessage::String
    - code::Int64
"""
Base.@kwdef mutable struct NotFoundErrorResponse <: OpenAPI.APIModel
    error::Union{Nothing, Any} = nothing
    errorNum::Union{Nothing, Int64} = nothing
    errorMessage::Union{Nothing, String} = nothing
    code::Union{Nothing, Int64} = nothing

    function NotFoundErrorResponse(error, errorNum, errorMessage, code, )
        o = new(error, errorNum, errorMessage, code, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type NotFoundErrorResponse

const _property_types_NotFoundErrorResponse = Dict{Symbol,String}(Symbol("error")=>"Any", Symbol("errorNum")=>"Int64", Symbol("errorMessage")=>"String", Symbol("code")=>"Int64", )
OpenAPI.property_type(::Type{ NotFoundErrorResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NotFoundErrorResponse[name]))}

function OpenAPI.check_required(o::NotFoundErrorResponse)
    o.error === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::NotFoundErrorResponse)
    OpenAPI.validate_property(NotFoundErrorResponse, Symbol("error"), o.error)
    OpenAPI.validate_property(NotFoundErrorResponse, Symbol("errorNum"), o.errorNum)
    OpenAPI.validate_property(NotFoundErrorResponse, Symbol("errorMessage"), o.errorMessage)
    OpenAPI.validate_property(NotFoundErrorResponse, Symbol("code"), o.code)
end

function OpenAPI.validate_property(::Type{ NotFoundErrorResponse }, name::Symbol, val)




end
