# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""claim_action_200_response

    ClaimAction200Response(;
        action_id=nothing,
        success=nothing,
    )

    - action_id::Int64
    - success::Bool
"""
Base.@kwdef mutable struct ClaimAction200Response <: OpenAPI.APIModel
    action_id::Union{Nothing, Int64} = nothing
    success::Union{Nothing, Bool} = nothing

    function ClaimAction200Response(action_id, success, )
        o = new(action_id, success, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ClaimAction200Response

const _property_types_ClaimAction200Response = Dict{Symbol,String}(Symbol("action_id")=>"Int64", Symbol("success")=>"Bool", )
OpenAPI.property_type(::Type{ ClaimAction200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ClaimAction200Response[name]))}

function OpenAPI.check_required(o::ClaimAction200Response)
    true
end

function OpenAPI.validate_properties(o::ClaimAction200Response)
    OpenAPI.validate_property(ClaimAction200Response, Symbol("action_id"), o.action_id)
    OpenAPI.validate_property(ClaimAction200Response, Symbol("success"), o.success)
end

function OpenAPI.validate_property(::Type{ ClaimAction200Response }, name::Symbol, val)


end
