# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_job_file_relationships_response

    ListJobFileRelationshipsResponse(;
        items=nothing,
        offset=nothing,
        max_limit=nothing,
        count=nothing,
        total_count=nothing,
        has_more=nothing,
    )

    - items::Vector{JobFileRelationshipModel}
    - offset::Int64
    - max_limit::Int64
    - count::Int64
    - total_count::Int64
    - has_more::Bool
"""
Base.@kwdef mutable struct ListJobFileRelationshipsResponse <: OpenAPI.APIModel
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobFileRelationshipModel} }
    offset::Union{Nothing, Int64} = nothing
    max_limit::Union{Nothing, Int64} = nothing
    count::Union{Nothing, Int64} = nothing
    total_count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing

    function ListJobFileRelationshipsResponse(items, offset, max_limit, count, total_count, has_more, )
        o = new(items, offset, max_limit, count, total_count, has_more, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ListJobFileRelationshipsResponse

const _property_types_ListJobFileRelationshipsResponse = Dict{Symbol,String}(Symbol("items")=>"Vector{JobFileRelationshipModel}", Symbol("offset")=>"Int64", Symbol("max_limit")=>"Int64", Symbol("count")=>"Int64", Symbol("total_count")=>"Int64", Symbol("has_more")=>"Bool", )
OpenAPI.property_type(::Type{ ListJobFileRelationshipsResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListJobFileRelationshipsResponse[name]))}

function OpenAPI.check_required(o::ListJobFileRelationshipsResponse)
    o.items === nothing && (return false)
    o.offset === nothing && (return false)
    o.max_limit === nothing && (return false)
    o.count === nothing && (return false)
    o.total_count === nothing && (return false)
    o.has_more === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ListJobFileRelationshipsResponse)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("items"), o.items)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("offset"), o.offset)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("max_limit"), o.max_limit)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("count"), o.count)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("total_count"), o.total_count)
    OpenAPI.validate_property(ListJobFileRelationshipsResponse, Symbol("has_more"), o.has_more)
end

function OpenAPI.validate_property(::Type{ ListJobFileRelationshipsResponse }, name::Symbol, val)






end
