# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""reset_job_status_response
Response from resetting job statuses

    ResetJobStatusResponse(;
        workflow_id=nothing,
        updated_count=nothing,
        status=nothing,
        reset_type=nothing,
    )

    - workflow_id::Int64 : The workflow ID for which jobs were reset
    - updated_count::Int64 : The number of jobs that were updated
    - status::String : The status that jobs were reset to
    - reset_type::String : The type of reset performed (e.g., \&quot;all\&quot; or \&quot;failed_only\&quot;)
"""
Base.@kwdef mutable struct ResetJobStatusResponse <: OpenAPI.APIModel
    workflow_id::Union{Nothing, Int64} = nothing
    updated_count::Union{Nothing, Int64} = nothing
    status::Union{Nothing, String} = nothing
    reset_type::Union{Nothing, String} = nothing

    function ResetJobStatusResponse(workflow_id, updated_count, status, reset_type, )
        o = new(workflow_id, updated_count, status, reset_type, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ResetJobStatusResponse

const _property_types_ResetJobStatusResponse = Dict{Symbol,String}(Symbol("workflow_id")=>"Int64", Symbol("updated_count")=>"Int64", Symbol("status")=>"String", Symbol("reset_type")=>"String", )
OpenAPI.property_type(::Type{ ResetJobStatusResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResetJobStatusResponse[name]))}

function OpenAPI.check_required(o::ResetJobStatusResponse)
    o.workflow_id === nothing && (return false)
    o.updated_count === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ResetJobStatusResponse)
    OpenAPI.validate_property(ResetJobStatusResponse, Symbol("workflow_id"), o.workflow_id)
    OpenAPI.validate_property(ResetJobStatusResponse, Symbol("updated_count"), o.updated_count)
    OpenAPI.validate_property(ResetJobStatusResponse, Symbol("status"), o.status)
    OpenAPI.validate_property(ResetJobStatusResponse, Symbol("reset_type"), o.reset_type)
end

function OpenAPI.validate_property(::Type{ ResetJobStatusResponse }, name::Symbol, val)




end
