# Resource Monitoring Demo Workflow
# This workflow demonstrates the resource monitoring feature with 3 independent jobs
# that consume CPU and memory for about a minute each.
#
# To run this workflow:
# 1. Start the torc server
# 2. Create the workflow: torc workflows create examples/resource_monitoring_demo.yaml
# 3. Initialize and start: torc workflows start <workflow_id>
# 4. Run the job runner: torc-job-runner <workflow_id>
# 5. Check results with resource metrics: torc results list <workflow_id>

name: resource_monitoring_demo
user: demo_user
description: Demonstrates resource monitoring with CPU and memory intensive Python jobs

# Enable resource monitoring with time-series data collection
resource_monitor:
  enabled: true
  granularity: "time_series"  # Options: "summary" or "time_series"
  sample_interval_seconds: 2   # Sample every 2 seconds
  generate_plots: false         # Not yet implemented

# Three independent jobs that run concurrently
jobs:
  - name: cpu_heavy_job
    command: "python3 examples/scripts/cpu_intensive.py"
    resource_requirements: medium

  - name: memory_heavy_job
    command: "python3 examples/scripts/memory_intensive.py"
    resource_requirements: medium

  - name: mixed_workload_job
    command: "python3 examples/scripts/mixed_workload.py"
    resource_requirements: medium

# No files needed for this demo
files: []

# No user data needed
user_data: []

# Resource requirements
resource_requirements:
  - name: medium
    num_cpus: 2
    num_gpus: 0
    num_nodes: 1
    memory: 2g
    runtime: PT5M  # ISO 8601 duration: 5 minutes

# No Slurm schedulers (runs locally)
slurm_schedulers: []
