name: "Simple Workflow with Actions"
user: "demo"
description: "Demonstrates scheduler actions for different workflow stages"

jobs:
  - name: "setup"
    command: "echo 'Setting up...' && sleep 2"
    resource_requirements: "small"

  - name: "process1"
    command: "echo 'Processing data...' && sleep 5"
    blocked_by: ["setup"]
    resource_requirements: "medium"

  - name: "process2"
    command: "echo 'Processing data...' && sleep 5"
    blocked_by: ["setup"]
    resource_requirements: "medium"

  - name: "process3"
    command: "echo 'Processing data...' && sleep 5"
    blocked_by: ["setup"]
    resource_requirements: "medium"

  - name: "finalize"
    command: "echo 'Finalizing...' && sleep 2"
    blocked_by: ["process1", "process2", "process3"]
    resource_requirements: "small"

resource_requirements:
  - name: "small"
    num_cpus: 2
    num_gpus: 0
    num_nodes: 1
    memory: "4g"
    runtime: "PT30M"

  - name: "medium"
    num_cpus: 8
    num_gpus: 0
    num_nodes: 1
    memory: "16g"
    runtime: "PT2H"

slurm_schedulers:
  # Small scheduler for setup stage
  - name: "setup_scheduler"
    account: "demo_project"
    nodes: 1
    walltime: "00:30:00"

  # Larger scheduler for compute-intensive processing stage
  - name: "process_scheduler"
    account: "demo_project"
    nodes: 1
    walltime: "02:00:00"

  # Medium scheduler for finalization stage
  - name: "finalize_scheduler"
    account: "demo_project"
    nodes: 1
    walltime: "00:30:00"

actions:
  # Allocate resources for setup stage
  - trigger_type: "on_workflow_start"
    action_type: "schedule_nodes"
    jobs: ["setup"]
    scheduler: "setup_scheduler"
    scheduler_type: "slurm"
    num_allocations: 1

  # Allocate resources for processing stage
  - trigger_type: "on_jobs_ready"
    action_type: "schedule_nodes"
    jobs: ["process1", "process2", "process3"]
    scheduler: "process_scheduler"
    scheduler_type: "slurm"
    num_allocations: 3

  # Allocate resources for finalization stage
  - trigger_type: "on_jobs_ready"
    action_type: "schedule_nodes"
    jobs: ["finalize"]
    scheduler: "finalize_scheduler"
    scheduler_type: "slurm"
    num_allocations: 1
