# coding: utf-8

"""
    torc

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.2.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import ConfigDict, BaseModel, Field, StrictStr

class EdgesNameModel(BaseModel):
    """
    EdgesNameModel
    """
    var_from: StrictStr = Field(..., alias="_from")
    to: StrictStr = Field(..., alias="_to")
    data: Optional[Dict[str, Any]] = None
    key: Optional[StrictStr] = Field(None, alias="_key")
    id: Optional[StrictStr] = Field(None, alias="_id")
    rev: Optional[StrictStr] = Field(None, alias="_rev")
    __properties = ["_from", "_to", "data", "_key", "_id", "_rev"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EdgesNameModel:
        """Create an instance of EdgesNameModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EdgesNameModel:
        """Create an instance of EdgesNameModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EdgesNameModel.model_validate(obj)

        _obj = EdgesNameModel.model_validate({
            "var_from": obj.get("_from"),
            "to": obj.get("_to"),
            "data": obj.get("data"),
            "key": obj.get("_key"),
            "id": obj.get("_id"),
            "rev": obj.get("_rev")
        })
        return _obj


