# coding: utf-8

"""
    torc

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.2.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import Field, ConfigDict, BaseModel, StrictStr
from typing_extensions import Annotated

class GetWorkflowsKeyMissingUserDataResponse(BaseModel):
    """
    GetWorkflowsKeyMissingUserDataResponse
    """
    user_data: Optional[Annotated[List[StrictStr], Field()]] = None
    __properties = ["user_data"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetWorkflowsKeyMissingUserDataResponse:
        """Create an instance of GetWorkflowsKeyMissingUserDataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetWorkflowsKeyMissingUserDataResponse:
        """Create an instance of GetWorkflowsKeyMissingUserDataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetWorkflowsKeyMissingUserDataResponse.model_validate(obj)

        _obj = GetWorkflowsKeyMissingUserDataResponse.model_validate({
            "user_data": obj.get("user_data")
        })
        return _obj


