# coding: utf-8

"""
    torc

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import ConfigDict, BaseModel, Field, StrictFloat, StrictInt, StrictStr

class GetWorkflowsKeyReadyJobRequirementsResponse(BaseModel):
    """
    GetWorkflowsKeyReadyJobRequirementsResponse
    """
    num_jobs: StrictInt = Field(...)
    num_cpus: StrictInt = Field(...)
    num_gpus: StrictInt = Field(...)
    memory_gb: Union[StrictFloat, StrictInt] = Field(...)
    max_memory_gb: Union[StrictFloat, StrictInt] = Field(...)
    max_num_nodes: StrictInt = Field(...)
    max_runtime: StrictStr = Field(...)
    __properties = ["num_jobs", "num_cpus", "num_gpus", "memory_gb", "max_memory_gb", "max_num_nodes", "max_runtime"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetWorkflowsKeyReadyJobRequirementsResponse:
        """Create an instance of GetWorkflowsKeyReadyJobRequirementsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetWorkflowsKeyReadyJobRequirementsResponse:
        """Create an instance of GetWorkflowsKeyReadyJobRequirementsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetWorkflowsKeyReadyJobRequirementsResponse.model_validate(obj)

        _obj = GetWorkflowsKeyReadyJobRequirementsResponse.model_validate({
            "num_jobs": obj.get("num_jobs"),
            "num_cpus": obj.get("num_cpus"),
            "num_gpus": obj.get("num_gpus"),
            "memory_gb": obj.get("memory_gb"),
            "max_memory_gb": obj.get("max_memory_gb"),
            "max_num_nodes": obj.get("max_num_nodes"),
            "max_runtime": obj.get("max_runtime")
        })
        return _obj


