# coding: utf-8

"""
    torc

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import ConfigDict, BaseModel, Field, StrictInt, StrictStr

class InlineResponse500(BaseModel):
    """
    InlineResponse500
    """
    error: Dict[str, Any] = Field(...)
    error_num: Optional[StrictInt] = Field(None, alias="errorNum")
    error_message: Optional[StrictStr] = Field(None, alias="errorMessage")
    code: Optional[StrictInt] = None
    __properties = ["error", "errorNum", "errorMessage", "code"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InlineResponse500:
        """Create an instance of InlineResponse500 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InlineResponse500:
        """Create an instance of InlineResponse500 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InlineResponse500.model_validate(obj)

        _obj = InlineResponse500.model_validate({
            "error": obj.get("error"),
            "error_num": obj.get("errorNum"),
            "error_message": obj.get("errorMessage"),
            "code": obj.get("code")
        })
        return _obj


