# coding: utf-8

"""
    torc

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import ConfigDict, BaseModel, Field, StrictBool, StrictStr
from typing_extensions import Annotated

class WorkflowJobSpecificationsModel(BaseModel):
    """
    WorkflowJobSpecificationsModel
    """
    name: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    command: StrictStr = Field(...)
    invocation_script: Optional[StrictStr] = None
    cancel_on_blocking_job_failure: Optional[StrictBool] = True
    supports_termination: Optional[StrictBool] = False
    scheduler: Optional[StrictStr] = None
    needs_compute_node_schedule: Optional[StrictBool] = False
    consumes_user_data: Optional[Annotated[List[StrictStr], Field()]] = None
    stores_user_data: Optional[Annotated[List[StrictStr], Field()]] = None
    resource_requirements: Optional[StrictStr] = None
    input_files: Optional[Annotated[List[StrictStr], Field()]] = None
    output_files: Optional[Annotated[List[StrictStr], Field()]] = None
    blocked_by: Optional[Annotated[List[StrictStr], Field()]] = None
    __properties = ["name", "key", "command", "invocation_script", "cancel_on_blocking_job_failure", "supports_termination", "scheduler", "needs_compute_node_schedule", "consumes_user_data", "stores_user_data", "resource_requirements", "input_files", "output_files", "blocked_by"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowJobSpecificationsModel:
        """Create an instance of WorkflowJobSpecificationsModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowJobSpecificationsModel:
        """Create an instance of WorkflowJobSpecificationsModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowJobSpecificationsModel.model_validate(obj)

        _obj = WorkflowJobSpecificationsModel.model_validate({
            "name": obj.get("name"),
            "key": obj.get("key"),
            "command": obj.get("command"),
            "invocation_script": obj.get("invocation_script"),
            "cancel_on_blocking_job_failure": obj.get("cancel_on_blocking_job_failure") if obj.get("cancel_on_blocking_job_failure") is not None else True,
            "supports_termination": obj.get("supports_termination") if obj.get("supports_termination") is not None else False,
            "scheduler": obj.get("scheduler"),
            "needs_compute_node_schedule": obj.get("needs_compute_node_schedule") if obj.get("needs_compute_node_schedule") is not None else False,
            "consumes_user_data": obj.get("consumes_user_data"),
            "stores_user_data": obj.get("stores_user_data"),
            "resource_requirements": obj.get("resource_requirements"),
            "input_files": obj.get("input_files"),
            "output_files": obj.get("output_files"),
            "blocked_by": obj.get("blocked_by")
        })
        return _obj


