# coding: utf-8

# flake8: noqa
"""
    torc

    Defines the API for the torc service.

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from torc.openapi_client.models.add_jobs_response import AddJobsResponse
from torc.openapi_client.models.claim_action200_response import ClaimAction200Response
from torc.openapi_client.models.claim_action_request import ClaimActionRequest
from torc.openapi_client.models.compute_node_model import ComputeNodeModel
from torc.openapi_client.models.compute_node_schedule import ComputeNodeSchedule
from torc.openapi_client.models.compute_nodes_resources import ComputeNodesResources
from torc.openapi_client.models.default_error_response import DefaultErrorResponse
from torc.openapi_client.models.event_model import EventModel
from torc.openapi_client.models.file_model import FileModel
from torc.openapi_client.models.get_ready_job_requirements_response import GetReadyJobRequirementsResponse
from torc.openapi_client.models.is_complete_response import IsCompleteResponse
from torc.openapi_client.models.is_uninitialized_response import IsUninitializedResponse
from torc.openapi_client.models.job_dependency_model import JobDependencyModel
from torc.openapi_client.models.job_model import JobModel
from torc.openapi_client.models.job_status import JobStatus
from torc.openapi_client.models.jobs_model import JobsModel
from torc.openapi_client.models.jobs_sort_method import JobsSortMethod
from torc.openapi_client.models.list_compute_nodes_response import ListComputeNodesResponse
from torc.openapi_client.models.list_events_response import ListEventsResponse
from torc.openapi_client.models.list_files_response import ListFilesResponse
from torc.openapi_client.models.list_job_dependencies_response import ListJobDependenciesResponse
from torc.openapi_client.models.list_jobs_response import ListJobsResponse
from torc.openapi_client.models.list_local_schedulers_response import ListLocalSchedulersResponse
from torc.openapi_client.models.list_missing_user_data_response import ListMissingUserDataResponse
from torc.openapi_client.models.list_required_existing_files_response import ListRequiredExistingFilesResponse
from torc.openapi_client.models.list_resource_requirements_response import ListResourceRequirementsResponse
from torc.openapi_client.models.list_results_response import ListResultsResponse
from torc.openapi_client.models.list_scheduled_compute_nodes_response import ListScheduledComputeNodesResponse
from torc.openapi_client.models.list_slurm_schedulers_response import ListSlurmSchedulersResponse
from torc.openapi_client.models.list_user_data_response import ListUserDataResponse
from torc.openapi_client.models.list_workflows_response import ListWorkflowsResponse
from torc.openapi_client.models.local_scheduler_model import LocalSchedulerModel
from torc.openapi_client.models.not_found_error_response import NotFoundErrorResponse
from torc.openapi_client.models.prepare_jobs_for_submission_response import PrepareJobsForSubmissionResponse
from torc.openapi_client.models.prepare_next_jobs_for_submission_response import PrepareNextJobsForSubmissionResponse
from torc.openapi_client.models.process_changed_job_inputs_response import ProcessChangedJobInputsResponse
from torc.openapi_client.models.resource_requirements_model import ResourceRequirementsModel
from torc.openapi_client.models.result_model import ResultModel
from torc.openapi_client.models.scheduled_compute_nodes_model import ScheduledComputeNodesModel
from torc.openapi_client.models.slurm_scheduler_model import SlurmSchedulerModel
from torc.openapi_client.models.user_data_model import UserDataModel
from torc.openapi_client.models.workflow_action_model import WorkflowActionModel
from torc.openapi_client.models.workflow_model import WorkflowModel
from torc.openapi_client.models.workflow_status_model import WorkflowStatusModel
