name: Pytest

on: pull_request

jobs:
  build:
    runs-on: viz-runners
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install './torc_package[dev]'
    - name: Setup ArangoDB
      uses: daniel-thom/arangodb-action@v1
    - name: Configure ArangoDB
      run: |
        apt-get update
        apt-get install -y npm zip curl docker podman
        curl -s -X POST http://127.0.0.1:8529/_db/_system/_api/database --data '{"name":"test-workflows"}'
        cd db_service
        npm install
        zip -r - manifest.json index.js node_modules src scripts | docker exec -i arangodb_container foxx install --server http://127.0.0.1:8529 -D test-workflows /torc-service @
        cd ..
        bash db_service/make_api.sh
    - name: Run pytest
      run: |
        python -m pytest -v --disable-warnings torc_package/tests
