name: Pytest

on: pull_request

jobs:
  build:
    runs-on: viz-runners
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install './torc_package[dev]'
    - name: Configure ArangoDB
      run: |
        apt-get update
        apt-get install -y zip curl podman
        podman run --name=arangodb -d -v $GITHUB_WORKSPACE:/data -p 8529:8529 docker.io/arangodb:3.11.4 arangodb --starter.mode=single --starter.address=127.0.0.1
        curl -X GET http://127.0.0.1:8529/_db/_system/_api/database
        curl -X POST http://127.0.0.1:8529/_db/_system/_api/database --data '{"name":"test-workflows"}'
        curl -X GET http://127.0.0.1:8529/_db/_system/_api/database
        zip -r torc-service.zip db_service/manifest.json db_service/index.js db_service/node_modules db_service/src db_service/scripts
        podman exec docker.io/arangodb:3.11.4 foxx install --server http://127.0.0.1:8529 -D test-workflows /torc-service /data/torc-service.zip
        bash db_service/make_api.sh
        rm torc-service.zip
    - name: Run pytest
      run: |
        python -m pytest -v --disable-warnings torc_package/tests
